import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js/+esm';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js/+esm';
import {RoomEnvironment} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/environments/RoomEnvironment.js/+esm';
import {RoundedBoxGeometry} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/geometries/RoundedBoxGeometry.js/+esm';
import * as SkeletonUtils from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/utils/SkeletonUtils.js/+esm';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const COLORS={skin:['#f3d1b8','#dda680','#bd7d58','#8b553b','#573224'],hair:['#1c1714','#4a3022','#86542f','#c69255','#8d3829'],eye:['#4b3325','#697252','#697f88','#375d79','#594b3d'],outfit:['#ded8cf','#30363a','#a18469','#65766b','#786879']};
const appearance={name:'Valentina',gender:'fem',skin:1,hair:0,eye:0,hairStyle:0,body:100,height:100,outfit:0,faceWidth:100,jaw:100,eyeSize:100,trait:'Sociable',aspiration:'Vida equilibrada'};
const needs={hunger:82,energy:77,hygiene:78,bladder:73,fun:74,social:72};
let mode='menu',speed=1,simMinutes=555,tvOn=false,peer=null,network=null,lastNetwork=0,graphicsHigh=true;

const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('#game').appendChild(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer),env=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const world=new THREE.Scene();world.background=new THREE.Color('#68757e');world.environment=env;
const studio=new THREE.Scene();studio.background=new THREE.Color('#646a6c');studio.environment=env;
const worldCam=new THREE.PerspectiveCamera(39,innerWidth/innerHeight,.05,100),studioCam=new THREE.PerspectiveCamera(31,innerWidth/innerHeight,.05,50);
worldCam.position.set(10.9,8.2,10.9);studioCam.position.set(0,1.45,4.45);
const worldCtl=new OrbitControls(worldCam,renderer.domElement);worldCtl.target.set(0,.78,0);worldCtl.enableDamping=true;worldCtl.dampingFactor=.055;worldCtl.minDistance=6.3;worldCtl.maxDistance=17;worldCtl.minPolarAngle=.58;worldCtl.maxPolarAngle=1.25;
const studioCtl=new OrbitControls(studioCam,renderer.domElement);studioCtl.target.set(0,1.02,0);studioCtl.enableDamping=true;studioCtl.enablePan=false;studioCtl.minDistance=2.3;studioCtl.maxDistance=5.2;studioCtl.maxPolarAngle=1.48;

function tex(draw,w=512,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t}
const wood=tex((c,w,h)=>{c.fillStyle='#765b45';c.fillRect(0,0,w,h);for(let y=0;y<h;y+=64){c.fillStyle=y%128?'#80634b':'#71543f';c.fillRect(0,y,w,61);c.strokeStyle='#493527';c.lineWidth=2.4;c.beginPath();c.moveTo(0,y+62);c.lineTo(w,y+62);c.stroke();for(let j=0;j<14;j++){let yy=y+7+Math.random()*48;c.strokeStyle='rgba(20,11,7,.11)';c.lineWidth=1;c.beginPath();c.moveTo(0,yy);c.bezierCurveTo(w*.33,yy+Math.random()*8-4,w*.66,yy+Math.random()*8-4,w,yy);c.stroke()}}});wood.repeat.set(2.7,3.5);
const tile=tex((c,w,h)=>{c.fillStyle='#c7c6c1';c.fillRect(0,0,w,h);c.strokeStyle='#979997';c.lineWidth=3;for(let i=0;i<=w;i+=128){c.beginPath();c.moveTo(i,0);c.lineTo(i,h);c.stroke()}for(let i=0;i<=h;i+=128){c.beginPath();c.moveTo(0,i);c.lineTo(w,i);c.stroke()}});tile.repeat.set(2.2,3.6);
const cloth=tex((c,w,h)=>{c.fillStyle='#656967';c.fillRect(0,0,w,h);c.strokeStyle='rgba(255,255,255,.035)';for(let i=0;i<w;i+=3){c.beginPath();c.moveTo(i,0);c.lineTo(i,h);c.stroke()}for(let i=0;i<h;i+=3){c.beginPath();c.moveTo(0,i);c.lineTo(w,i);c.stroke()}});cloth.repeat.set(4,4);
const city=tex((c,w,h)=>{let g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#6f90aa');g.addColorStop(.4,'#d39b78');g.addColorStop(.66,'#525761');g.addColorStop(1,'#15191f');c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle='#222832';for(let i=0;i<55;i++){let x=Math.random()*w,bw=8+Math.random()*25,bh=32+Math.random()*180;c.fillRect(x,h-bh,bw,bh);c.fillStyle='rgba(255,214,132,.72)';for(let yy=h-bh+12;yy<h-8;yy+=14)for(let xx=x+5;xx<x+bw-4;xx+=9)if(Math.random()>.6)c.fillRect(xx,yy,2.4,4);c.fillStyle='#222832'}c.fillStyle='#ffd49f';c.globalAlpha=.75;c.beginPath();c.arc(w*.78,h*.27,19,0,7);c.fill();c.globalAlpha=1});
const art=tex((c,w,h)=>{c.fillStyle='#dbd1c5';c.fillRect(0,0,w,h);c.fillStyle='#475956';c.fillRect(45,70,125,300);c.fillStyle='#96775f';c.fillRect(190,42,112,350);c.fillStyle='#7b8d8e';c.beginPath();c.arc(392,210,88,0,7);c.fill();c.fillStyle='#c6aa89';c.fillRect(342,305,104,70)});
const M={wall:new THREE.MeshStandardMaterial({color:'#d8d1c7',roughness:.93}),wall2:new THREE.MeshStandardMaterial({color:'#c7bfb4',roughness:.93}),wood:new THREE.MeshStandardMaterial({map:wood,roughness:.79}),tile:new THREE.MeshStandardMaterial({map:tile,roughness:.38}),white:new THREE.MeshStandardMaterial({color:'#eee9e1',roughness:.88}),ceramic:new THREE.MeshStandardMaterial({color:'#f4f1ec',roughness:.4}),dark:new THREE.MeshStandardMaterial({color:'#584235',roughness:.72}),black:new THREE.MeshStandardMaterial({color:'#151719',roughness:.22,metalness:.28}),fabric:new THREE.MeshStandardMaterial({map:cloth,roughness:.97}),chrome:new THREE.MeshStandardMaterial({color:'#adb3b7',roughness:.15,metalness:.84}),glass:new THREE.MeshPhysicalMaterial({color:'#bdd2d8',roughness:.06,transmission:.55,transparent:true,opacity:.48}),rug:new THREE.MeshStandardMaterial({color:'#b6aea2',roughness:1}),green:new THREE.MeshStandardMaterial({color:'#506c4c',roughness:.92})};
const rb=(s,p,m=M.white,r=.08)=>{const o=new THREE.Mesh(new RoundedBoxGeometry(s[0],s[1],s[2],5,r),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const bx=(s,p,m=M.white)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const cy=(r1,r2,h,p,m=M.white,seg=32)=>{const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,seg),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const sp=(r,p,m=M.white,seg=30)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(r,seg,20),m);o.position.set(...p);o.castShadow=true;return o};

const home=new THREE.Group();world.add(home);const objects={},collisions=[];let screenMat;
function interactive(id,label,desc,group,approach,actions,bounds){group.traverse(o=>{if(o.isMesh)o.userData.interactive=id});home.add(group);objects[id]={id,label,desc,group,approach:new THREE.Vector3(...approach),actions};if(bounds)collisions.push({id,...bounds})}
function collision(id,x,z,w,d){collisions.push({id,x,z,w,d})}
function buildHome(){
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,10),M.wood);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;floor.userData.floor=true;home.add(floor);
 const bathFloor=new THREE.Mesh(new THREE.PlaneGeometry(2.6,4.55),M.tile);bathFloor.rotation.x=-Math.PI/2;bathFloor.position.set(4.55,.018,2.45);bathFloor.receiveShadow=true;bathFloor.userData.floor=true;home.add(bathFloor);
 home.add(bx([12,3.55,.16],[0,1.775,-5],M.wall),bx([.16,3.55,10],[-6,1.775,0],M.wall),bx([.14,3.2,3.92],[3.3,1.6,3.02],M.wall2),bx([2.72,3.2,.14],[4.65,1.6,4.87],M.wall2));collision('partition',3.3,3.02,.22,3.98);
 const skyline=new THREE.Mesh(new THREE.PlaneGeometry(4.42,2.42),new THREE.MeshBasicMaterial({map:city,toneMapped:false}));skyline.position.set(-2.85,1.97,-4.9);home.add(skyline);const fm=new THREE.MeshStandardMaterial({color:'#1d2225',roughness:.24,metalness:.55});home.add(bx([4.58,.07,.08],[-2.85,.76,-4.78],fm),bx([4.58,.07,.08],[-2.85,3.18,-4.78],fm),bx([.07,2.43,.08],[-5.13,1.97,-4.78],fm),bx([.07,2.43,.08],[-.57,1.97,-4.78],fm),bx([.05,2.39,.08],[-2.85,1.97,-4.76],fm));
 const curtainMat=new THREE.MeshStandardMaterial({color:'#cdc4b8',roughness:1,side:THREE.DoubleSide});for(const x of[-5.45,-.25]){const cu=rb([.3,2.65,.16],[x,1.88,-4.62],curtainMat,.08);cu.rotation.z=x<0?.018:-.018;home.add(cu)}
 const bed=new THREE.Group();bed.position.set(-3.55,0,-2.5);bed.add(rb([3.22,.42,2.26],[0,.28,0],M.dark,.08),rb([3.07,.34,2.1],[0,.59,0],M.white,.14),rb([3.0,.23,1.57],[0,.81,.19],new THREE.MeshStandardMaterial({color:'#aaa297',roughness:.98}),.11),rb([1.15,.23,.61],[-.7,.94,-.63],M.white,.15),rb([1.15,.23,.61],[.7,.94,-.63],M.white,.15),rb([3.24,1.26,.17],[0,1.13,-1.04],M.dark,.05));interactive('bed','Cama','Cama doble con ropa de cama y almohadas.',bed,[-3.55,0,-.92],[['Dormir','sleep'],['Sentarse','sitBed'],['Hacer la cama','makeBed']],{x:-3.55,z:-2.5,w:3.42,d:2.52});
 const night=rb([.78,.73,.74],[-5.16,.39,-2.62],M.dark,.07);home.add(night,rb([.54,.08,.45],[-5.16,.49,-2.23],M.black,.04),cy(.16,.18,.08,[-5.16,.8,-2.62],M.chrome),cy(.035,.035,.53,[-5.16,1.09,-2.62],M.chrome),cy(.29,.19,.34,[-5.16,1.44,-2.62],new THREE.MeshStandardMaterial({color:'#ead8b6',roughness:.85})));collision('night',-5.16,-2.62,.92,.92);
 const tv=new THREE.Group();tv.position.set(1.05,0,-4.72);tv.add(rb([3.06,1.72,.12],[0,1.74,0],M.black,.055));screenMat=new THREE.MeshStandardMaterial({color:'#101315',roughness:.16,emissive:'#000',emissiveIntensity:0});tv.add(bx([2.82,1.47,.035],[0,1.74,.08],screenMat),rb([3.52,.56,.72],[0,.39,.36],M.dark,.07),bx([2.75,.09,.5],[0,.67,.39],M.black));interactive('tv','Televisor','Televisor de gran formato frente al sofá.',tv,[1.05,0,-2.72],[['Ver televisión','watchTV'],['Encender / apagar','toggleTV']],{x:1.05,z:-4.45,w:3.78,d:.9});
 const sofa=new THREE.Group();sofa.position.set(1.0,0,-1.48);sofa.add(rb([2.96,.64,1.2],[0,.47,0],M.fabric,.16),rb([2.77,.74,.33],[0,.98,.39],M.fabric,.13),rb([.31,.59,1.12],[-1.37,.75,0],M.fabric,.12),rb([.31,.59,1.12],[1.37,.75,0],M.fabric,.12),rb([1.17,.13,.59],[-.66,.79,-.06],new THREE.MeshStandardMaterial({color:'#777972',roughness:.97}),.09),rb([1.17,.13,.59],[.66,.79,-.06],new THREE.MeshStandardMaterial({color:'#777972',roughness:.97}),.09));interactive('sofa','Sofá','Sofá tapizado de tres plazas.',sofa,[1.0,0,-.4],[['Sentarse','sitSofa'],['Relajarse','relax']],{x:1,z:-1.48,w:3.18,d:1.48});
 const rug=new THREE.Mesh(new THREE.PlaneGeometry(4.35,2.8),M.rug);rug.rotation.x=-Math.PI/2;rug.position.set(1,.025,-1.55);rug.receiveShadow=true;home.add(rug);
 const coffee=new THREE.Group();coffee.position.set(1,0,.03);coffee.add(rb([1.58,.12,.8],[0,.44,0],M.dark,.07),cy(.055,.055,.43,[-.64,.22,-.28],M.chrome),cy(.055,.055,.43,[.64,.22,-.28],M.chrome),cy(.055,.055,.43,[-.64,.22,.28],M.chrome),cy(.055,.055,.43,[.64,.22,.28],M.chrome));home.add(coffee);collision('coffee',1,.03,1.78,1.0);
 const desk=new THREE.Group();desk.position.set(-4.55,0,1.75);desk.add(rb([2.0,.12,.72],[0,.78,0],M.dark,.06),bx([.1,.75,.58],[-.82,.39,0],M.dark),bx([.1,.75,.58],[.82,.39,0],M.dark),rb([.95,.72,.08],[0,1.35,-.29],new THREE.MeshStandardMaterial({color:'#88979b',roughness:.07,metalness:.58}),.04));home.add(desk);collision('desk',-4.55,1.75,2.2,1.0);
 const chair=new THREE.Group();chair.position.set(-4.55,0,.85);chair.add(rb([.58,.48,.58],[0,.4,0],M.fabric,.09),rb([.58,.74,.13],[0,.93,.24],M.fabric,.06));home.add(chair);collision('deskchair',-4.55,.85,.78,.78);
 const shelf=new THREE.Group();shelf.position.set(2.45,0,1.7);shelf.add(bx([1.25,2.6,.4],[0,1.3,0],M.dark));for(const y of[.45,1.05,1.65,2.25])shelf.add(bx([1.15,.06,.48],[0,y,.02],M.black));for(let i=0;i<12;i++){const b=rb([.06+Math.random()*.035,.3+Math.random()*.15,.26],[-.48+(i%4)*.29,.45+Math.floor(i/4)*.6,.06],new THREE.MeshStandardMaterial({color:['#7d6757','#5f7377','#99836a','#4f5658'][i%4],roughness:.9}),.015);shelf.add(b)}home.add(shelf);collision('shelf',2.45,1.7,1.45,.68);
 const toilet=new THREE.Group();toilet.position.set(5.15,0,3.68);toilet.add(rb([.61,.53,.75],[0,.29,0],M.ceramic,.13),rb([.65,.73,.28],[0,.67,.31],M.ceramic,.08));const seat=new THREE.Mesh(new THREE.TorusGeometry(.265,.05,12,32),M.ceramic);seat.rotation.x=Math.PI/2;seat.scale.z=1.26;seat.position.set(0,.59,-.05);toilet.add(seat);interactive('toilet','Inodoro','Inodoro de porcelana.',toilet,[5.15,0,2.7],[['Usar','toilet']],{x:5.15,z:3.68,w:.88,d:1.07});
 const sink=new THREE.Group();sink.position.set(4.03,0,3.82);sink.add(rb([1.12,.74,.64],[0,.39,0],M.dark,.07),rb([1.05,.23,.62],[0,.83,0],M.ceramic,.1),cy(.035,.035,.35,[0,1.0,.14],M.chrome));const basin=new THREE.Mesh(new THREE.TorusGeometry(.31,.06,10,30),M.ceramic);basin.rotation.x=Math.PI/2;basin.scale.z=.7;basin.position.set(0,.9,-.05);sink.add(basin);const mirror=new THREE.Mesh(new THREE.PlaneGeometry(1.15,1.3),new THREE.MeshStandardMaterial({color:'#93a1a7',roughness:.05,metalness:.69}));mirror.position.set(0,1.77,.34);mirror.rotation.y=Math.PI;sink.add(mirror);interactive('sink','Lavamanos','Vanitorio con espejo y grifería cromada.',sink,[4.03,0,2.7],[['Lavarse las manos','wash'],['Mirarse al espejo','mirror']],{x:4.03,z:3.82,w:1.3,d:.92});
 const shower=new THREE.Group();shower.position.set(4.65,0,1.25);shower.add(rb([1.86,.14,1.58],[0,.08,0],M.ceramic,.05),bx([.05,2.38,1.58],[-.9,1.22,0],M.glass),bx([1.84,2.38,.05],[0,1.22,-.77],M.glass),cy(.035,.035,1.82,[.56,1.37,-.6],M.chrome),sp(.12,[.56,2.22,-.46],M.chrome));interactive('shower','Ducha','Ducha de vidrio con agua caliente.',shower,[4.65,0,.08],[['Ducharse','shower']],{x:4.65,z:1.25,w:2.05,d:1.94});
 const bathMat=new THREE.Mesh(new THREE.PlaneGeometry(1.48,.74),new THREE.MeshStandardMaterial({color:'#888f8b',roughness:1}));bathMat.rotation.x=-Math.PI/2;bathMat.position.set(4.66,.029,2.35);home.add(bathMat);home.add(cy(.025,.025,1.12,[5.56,1.26,2.15],M.chrome));const towel=rb([.64,.72,.045],[5.54,1.18,2.15],new THREE.MeshStandardMaterial({color:'#d9d2c8',roughness:1}),.03);towel.rotation.y=Math.PI/2;home.add(towel);
 const plant=new THREE.Group();plant.position.set(2.55,0,-3.7);plant.add(cy(.23,.31,.52,[0,.26,0],new THREE.MeshStandardMaterial({color:'#b8aa96',roughness:.9})));for(let i=0;i<14;i++){const l=sp(.22,[Math.cos(i*.49)*.23,.74+Math.random()*.36,Math.sin(i*.49)*.23],M.green);l.scale.set(.5,1.74,.38);plant.add(l)}home.add(plant);collision('plant',2.55,-3.7,.72,.72);
 const painting=new THREE.Mesh(new THREE.PlaneGeometry(1.85,1.3),new THREE.MeshStandardMaterial({map:art,roughness:.8}));painting.position.set(-.8,2.15,-4.89);home.add(painting,bx([2.04,.06,.07],[-.8,2.83,-4.83],M.dark),bx([2.04,.06,.07],[-.8,1.47,-4.83],M.dark),bx([.06,1.42,.07],[-1.82,2.15,-4.83],M.dark),bx([.06,1.42,.07],[.22,2.15,-4.83],M.dark));
 const sun=new THREE.DirectionalLight('#ffd1a0',2.4);sun.position.set(-5,7,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-8;sun.shadow.camera.right=8;sun.shadow.camera.top=8;sun.shadow.camera.bottom=-8;world.add(sun,new THREE.HemisphereLight('#bcd2e3','#57483e',1.5));const lamp=new THREE.PointLight('#ffd9a7',12,5,2);lamp.position.set(-5.16,1.57,-2.62);world.add(lamp);const fill=new THREE.PointLight('#fff0dc',8,8,2);fill.position.set(1.8,3.1,.3);world.add(fill);
}
buildHome();

const player={holder:new THREE.Group(),pos:new THREE.Vector3(-.65,0,.72),path:[],action:null,bones:{},modelKind:null};world.add(player.holder);player.holder.position.copy(player.pos);
const studioHolder=new THREE.Group();studio.add(studioHolder);const remoteHolder=new THREE.Group();remoteHolder.visible=false;world.add(remoteHolder);
const loader=new GLTFLoader(),modelCache={};
const MODEL_URL={fem:'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r180/examples/models/gltf/Michelle.glb',masc:'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r180/examples/models/gltf/Xbot.glb'};
function fallbackHuman(){const g=new THREE.Group(),skin=new THREE.MeshStandardMaterial({color:COLORS.skin[appearance.skin],roughness:.7}),hair=new THREE.MeshStandardMaterial({color:COLORS.hair[appearance.hair],roughness:.9}),clothM=new THREE.MeshStandardMaterial({color:COLORS.outfit[appearance.outfit],roughness:.9}),pants=new THREE.MeshStandardMaterial({color:'#35393c',roughness:.9});const head=sp(.22,[0,1.65,0],skin);head.scale.set(.88,1.06,.92);g.add(head);const cap=sp(.235,[0,1.78,-.02],hair);cap.scale.set(1,.65,1);g.add(cap);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.27,.55,8,18),clothM);torso.position.y=1.08;g.add(torso);for(const x of[-.15,.15]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.68,6,12),pants);leg.position.set(x,.4,0);g.add(leg)}return g}
function prepModel(scene){const box=new THREE.Box3().setFromObject(scene),size=box.getSize(new THREE.Vector3()),scale=1.72/Math.max(.1,size.y);scene.scale.setScalar(scale);const b2=new THREE.Box3().setFromObject(scene);scene.position.y-=b2.min.y;scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material)o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone()}});return scene}
function applyTint(root){const skin=COLORS.skin[appearance.skin],hair=COLORS.hair[appearance.hair],out=COLORS.outfit[appearance.outfit];root.scale.x*=appearance.body/100;root.scale.z*=appearance.body/100;root.scale.y*=appearance.height/100;root.traverse(o=>{if(!o.isMesh)return;const n=(o.name+' '+(o.material?.name||'')).toLowerCase(),paint=m=>{if(!m?.color)return;if(n.includes('hair'))m.color.lerp(new THREE.Color(hair),.35);else if(n.includes('skin')||n.includes('body')||n.includes('head'))m.color.lerp(new THREE.Color(skin),.12);else if(n.includes('shirt')||n.includes('top')||n.includes('outfit')||n.includes('cloth'))m.color.lerp(new THREE.Color(out),.28)};Array.isArray(o.material)?o.material.forEach(paint):paint(o.material)})}
function findBones(root){const b={};root.traverse(o=>{if(!o.isBone)return;const n=o.name.toLowerCase().replace(/[_:\-.]/g,'');const put=(key,parts)=>{if(parts.some(p=>n.includes(p)))b[key]=o};put('leftLeg',['leftupleg','leftupperleg','leftthigh']);put('rightLeg',['rightupleg','rightupperleg','rightthigh']);put('leftArm',['leftarm','leftupperarm']);put('rightArm',['rightarm','rightupperarm'])});return b}
async function modelTemplate(kind){if(modelCache[kind])return modelCache[kind];const gltf=await loader.loadAsync(MODEL_URL[kind]);modelCache[kind]=prepModel(gltf.scene);return modelCache[kind]}
async function rebuildCharacter(){const kind=appearance.gender==='masc'?'masc':'fem';$('#creatorLoading').textContent='Cargando personaje 3D…';try{const base=await modelTemplate(kind),a=SkeletonUtils.clone(base),b=SkeletonUtils.clone(base);applyTint(a);applyTint(b);player.holder.clear();player.holder.add(a);studioHolder.clear();studioHolder.add(b);player.bones=findBones(a);player.modelKind=kind;$('#creatorLoading').textContent='Personaje 3D listo'}catch(e){player.holder.clear();player.holder.add(fallbackHuman());studioHolder.clear();studioHolder.add(fallbackHuman());player.bones={};$('#creatorLoading').textContent='Personaje local listo'}portrait()}
const studioFloor=new THREE.Mesh(new THREE.CircleGeometry(3.2,64),new THREE.MeshStandardMaterial({color:'#66635f',roughness:.82}));studioFloor.rotation.x=-Math.PI/2;studioFloor.receiveShadow=true;studio.add(studioFloor,new THREE.HemisphereLight('#dce8f0','#554842',1.8));const keyLight=new THREE.DirectionalLight('#ffe3ca',3.4);keyLight.position.set(4,6,5);keyLight.castShadow=true;studio.add(keyLight);const rim=new THREE.SpotLight('#bfdcff',22,8,.5,.8,1);rim.position.set(-3,4,2);studio.add(rim);rebuildCharacter();
function portrait(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');let g=x.createLinearGradient(0,0,0,128);g.addColorStop(0,'#d6e1e7');g.addColorStop(1,'#7a878e');x.fillStyle=g;x.fillRect(0,0,128,128);x.fillStyle=COLORS.hair[appearance.hair];x.beginPath();x.arc(64,53,34,Math.PI,Math.PI*2);x.fill();x.fillStyle=COLORS.skin[appearance.skin];x.beginPath();x.ellipse(64,61,29*appearance.faceWidth/100,35,0,0,7);x.fill();x.fillStyle=COLORS.eye[appearance.eye];for(const q of[50,78]){x.beginPath();x.arc(q,58,4.2*appearance.eyeSize/100,0,7);x.fill()}x.strokeStyle='#774f4f';x.lineWidth=2;x.beginPath();x.arc(64,70,10,.2,Math.PI-.2);x.stroke();$('#portrait').style.backgroundImage=`url(${c.toDataURL()})`}

function isBlocked(x,z,ignore){if(x<-5.62||x>5.62||z<-4.62||z>4.62)return true;for(const c of collisions){if(c.id===ignore)continue;if(Math.abs(x-c.x)<c.w/2+.18&&Math.abs(z-c.z)<c.d/2+.18)return true}return false}
const CELL=.28,X0=-5.55,Z0=-4.55,NX=Math.floor(11.1/CELL)+1,NZ=Math.floor(9.1/CELL)+1;
function findPath(from,to,ignore){const toCell=v=>[Math.max(0,Math.min(NX-1,Math.round((v.x-X0)/CELL))),Math.max(0,Math.min(NZ-1,Math.round((v.z-Z0)/CELL)))],key=(x,z)=>x+','+z;const [sx,sz]=toCell(from),[tx,tz]=toCell(to),open=[{x:sx,z:sz,g:0,f:0}],best=new Map([[key(sx,sz),0]]),came=new Map(),dirs=[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1],[1,1,1.414],[1,-1,1.414],[-1,1,1.414],[-1,-1,1.414]];let end=null,guard=0;while(open.length&&guard++<5000){open.sort((a,b)=>a.f-b.f);const n=open.shift();if(n.x===tx&&n.z===tz){end=n;break}for(const [dx,dz,cost] of dirs){const x=n.x+dx,z=n.z+dz;if(x<0||z<0||x>=NX||z>=NZ)continue;const wx=X0+x*CELL,wz=Z0+z*CELL;if(isBlocked(wx,wz,ignore)&&!(x===tx&&z===tz))continue;const g=n.g+cost,k=key(x,z);if(g>=(best.get(k)??Infinity))continue;best.set(k,g);came.set(k,key(n.x,n.z));open.push({x,z,g,f:g+Math.hypot(tx-x,tz-z)})}}if(!end)return[to.clone()];const cells=[];let k=key(tx,tz);cells.push([tx,tz]);while(k!==key(sx,sz)){const p=came.get(k);if(!p)break;const [x,z]=p.split(',').map(Number);cells.push([x,z]);k=p}cells.reverse();const path=[];for(let i=1;i<cells.length;i+=2){const [x,z]=cells[i];path.push(new THREE.Vector3(X0+x*CELL,0,Z0+z*CELL))}path.push(to.clone());return path}
function go(v,action=null){player.action=action;player.path=findPath(player.pos,v,action?.id||null)}
function manualStep(dx,dz,d=.09){if(mode!=='game'||player.action?.locked)return;const l=Math.hypot(dx,dz)||1,nx=player.pos.x+dx/l*d,nz=player.pos.z+dz/l*d;if(!isBlocked(nx,nz,null)){player.pos.set(nx,0,nz);player.holder.position.x=nx;player.holder.position.z=nz;player.holder.rotation.y=Math.atan2(dx,dz);player.path=[];player.action=null;sendState()}}
function animateRig(t,moving){const b=player.bones,s=moving?Math.sin(t*8.5)*.5:Math.sin(t*1.7)*.012;if(b.leftLeg)b.leftLeg.rotation.x=s;if(b.rightLeg)b.rightLeg.rotation.x=-s;if(b.leftArm)b.leftArm.rotation.x=-s*.7;if(b.rightArm)b.rightArm.rotation.x=s*.7;player.holder.position.y=moving?Math.abs(Math.sin(t*8.5))*.012:0}
function choose(id){const o=objects[id];if(!o)return;$('#contextTitle').textContent=o.label;$('#contextDescription').textContent=o.desc;const h=$('#contextActions');h.innerHTML='';for(const [label,a] of o.actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>queue(id,a);h.appendChild(b)}$('#contextMenu').classList.add('on')}
function queue(id,a){const o=objects[id];$('#contextMenu').classList.remove('on');go(o.approach,{id,a,pending:true,locked:false});notify(`Yendo a ${o.label.toLowerCase()}…`)}
function resetPose(){player.holder.visible=true;player.holder.rotation.z=0;player.holder.rotation.x=0;player.holder.position.set(player.pos.x,0,player.pos.z)}
function actionDone(ms,msg,change={},pose){notify(msg);if(pose)pose();setTimeout(()=>{for(const [k,v] of Object.entries(change))needs[k]=Math.min(100,needs[k]+v);player.action=null;resetPose();hud();save()},ms)}
function execute(a){a.pending=false;a.locked=true;switch(a.a){case'toggleTV':tvOn=!tvOn;screenMat.color.set(tvOn?'#4c91b8':'#101315');screenMat.emissive.set(tvOn?'#4c91b8':'#000');screenMat.emissiveIntensity=tvOn?1.7:0;player.action=null;notify(tvOn?'Televisor encendido':'Televisor apagado');break;case'watchTV':tvOn=true;screenMat.color.set('#4c91b8');screenMat.emissive.set('#4c91b8');screenMat.emissiveIntensity=1.7;actionDone(4200,'Viendo televisión',{fun:28},()=>{player.holder.position.set(1,.18,-1.5);player.holder.rotation.y=Math.PI});break;case'sitSofa':case'relax':actionDone(3200,a.a==='relax'?'Relajándose':'Sentada en el sofá',{energy:9,fun:8},()=>{player.holder.position.set(1,.18,-1.48);player.holder.rotation.y=Math.PI});break;case'sleep':actionDone(5200,'Durmiendo…',{energy:48},()=>{player.holder.position.set(-3.55,.78,-2.45);player.holder.rotation.z=-Math.PI/2});break;case'sitBed':actionDone(2800,'Descansando en la cama',{energy:11},()=>{player.holder.position.set(-3.55,.48,-1.72)});break;case'makeBed':actionDone(1200,'Cama ordenada');break;case'toilet':actionDone(3000,'Usando el baño',{bladder:50},()=>{player.holder.position.set(5.15,.12,3.45);player.holder.rotation.y=0});break;case'wash':actionDone(2200,'Lavándose las manos',{hygiene:18});break;case'mirror':actionDone(2200,'Mirándose al espejo',{fun:4});break;case'shower':player.holder.visible=false;actionDone(4100,'Duchándose',{hygiene:50});break}}
function notify(s){const t=$('#toast');t.textContent=s;t.classList.add('on');clearTimeout(notify.i);notify.i=setTimeout(()=>t.classList.remove('on'),1800)}
function hud(){for(const k of Object.keys(needs)){const e=$(`#${k}Bar`);if(e)e.style.width=Math.max(0,Math.min(100,needs[k]))+'%'}const a=Object.values(needs).reduce((x,y)=>x+y,0)/6;$('#mood').textContent=a>68?'● Cómoda':a>44?'● Normal':'● Incómoda'}

const keys=new Set();addEventListener('keydown',e=>{if(!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))keys.add(e.key.toLowerCase())});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let press=null,moved=false;renderer.domElement.addEventListener('pointerdown',e=>{press=[e.clientX,e.clientY];moved=false});renderer.domElement.addEventListener('pointermove',e=>{if(press&&Math.hypot(e.clientX-press[0],e.clientY-press[1])>7)moved=true});renderer.domElement.addEventListener('pointerup',e=>{if(mode!=='game'||moved){press=null;return}mouse.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight)*2+1);ray.setFromCamera(mouse,worldCam);for(const hit of ray.intersectObjects(home.children,true)){let n=hit.object;while(n&&n!==home){if(n.userData?.interactive){choose(n.userData.interactive);press=null;return}n=n.parent}if(hit.object.userData.floor){const p=hit.point.clone();p.y=0;if(!isBlocked(p.x,p.z,null))go(p);press=null;return}}press=null});

function setMode(m){mode=m;$('#menuScreen').classList.toggle('hidden',m!=='menu');$('#creatorScreen').classList.toggle('hidden',m!=='creator');$('#multiplayerScreen').classList.toggle('hidden',m!=='multi');$('#hud').classList.toggle('hidden',m!=='game');worldCtl.enabled=m==='menu'||m==='game';studioCtl.enabled=m==='creator';if(m==='game'){worldCam.position.set(10.9,8.2,10.9);worldCtl.target.set(0,.78,0);worldCtl.update();hud()}save()}
async function updateLook(reload=false){appearance.name=$('#charName').value.trim()||'Valentina';appearance.hairStyle=+$('#hairStyle').value;appearance.body=+$('#bodySize').value;appearance.height=+$('#height').value;appearance.outfit=+$('#outfit').value;appearance.faceWidth=+$('#faceWidth').value;appearance.jaw=+$('#jaw').value;appearance.eyeSize=+$('#eyeSize').value;appearance.trait=$('#trait').value;appearance.aspiration=$('#aspiration').value;$('#hudName').textContent=appearance.name;if(reload||player.modelKind!==(appearance.gender==='masc'?'masc':'fem'))await rebuildCharacter();else{await rebuildCharacter()}portrait();save()}
$('#continueBtn').onclick=()=>setMode('game');$('#newGameBtn').onclick=()=>setMode('creator');$('#createBtn').onclick=()=>setMode('creator');$('#multiplayerBtn').onclick=()=>setMode('multi');$('#creatorBack').onclick=()=>setMode('menu');$('#enterHome').onclick=async()=>{await updateLook();setMode('game')};$('#multiBack').onclick=()=>setMode('menu');$('#editCharacter').onclick=()=>setMode('creator');$('#menuBtn').onclick=()=>setMode('menu');$('#socialBtn').onclick=()=>setMode('multi');$('#settingsBtn').onclick=()=>{graphicsHigh=!graphicsHigh;renderer.setPixelRatio(Math.min(devicePixelRatio,graphicsHigh?2:1.25));renderer.shadowMap.enabled=graphicsHigh;notify(graphicsHigh?'Calidad alta':'Modo rendimiento')};$('#homeCamera').onclick=()=>{worldCam.position.set(10.9,8.2,10.9);worldCtl.target.set(0,.78,0);worldCtl.update()};
$$('.speed button').forEach(b=>b.onclick=()=>{$$('.speed button').forEach(x=>x.classList.remove('on'));b.classList.add('on');speed=+b.dataset.speed});$$('.creator-nav button').forEach(b=>b.onclick=()=>{$$('.creator-nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$$('.creator-tab').forEach(x=>x.classList.add('hidden'));$(`#tab-${b.dataset.tab}`).classList.remove('hidden')});$$('[data-gender]').forEach(b=>b.onclick=async()=>{$$('[data-gender]').forEach(x=>x.classList.remove('on'));b.classList.add('on');appearance.gender=b.dataset.gender;await rebuildCharacter();save()});
function swatches(host,arr,key){const h=$(host);arr.forEach((c,i)=>{const b=document.createElement('button');b.className='swatch'+(appearance[key]===i?' on':'');b.style.background=c;b.onclick=async()=>{appearance[key]=i;[...h.children].forEach(x=>x.classList.remove('on'));b.classList.add('on');await rebuildCharacter();portrait();save()};h.appendChild(b)})}swatches('#skinSwatches',COLORS.skin,'skin');swatches('#hairSwatches',COLORS.hair,'hair');swatches('#eyeSwatches',COLORS.eye,'eye');swatches('#outfitSwatches',COLORS.outfit,'outfit');['charName','hairStyle','bodySize','height','outfit','faceWidth','jaw','eyeSize','trait','aspiration'].forEach(id=>$('#'+id)?.addEventListener('change',()=>updateLook()));
$$('.mobile-pad button').forEach(b=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];let i;const f=()=>manualStep(d[0],d[1],.1);b.onpointerdown=e=>{e.preventDefault();f();i=setInterval(f,48)};['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>clearInterval(i)))});

function save(){try{localStorage.setItem('sims-tan-real',JSON.stringify({appearance,needs,simMinutes,p:[player.pos.x,player.pos.z],tvOn}))}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem('sims-tan-real')||'null');if(!s)return;Object.assign(appearance,s.appearance||{});Object.assign(needs,s.needs||{});if(s.simMinutes)simMinutes=s.simMinutes;if(s.p){player.pos.set(s.p[0],0,s.p[1]);player.holder.position.copy(player.pos)}tvOn=!!s.tvOn;$('#charName').value=appearance.name;$('#hairStyle').value=appearance.hairStyle;$('#bodySize').value=appearance.body;$('#height').value=appearance.height;$('#outfit').value=appearance.outfit;$('#faceWidth').value=appearance.faceWidth;$('#jaw').value=appearance.jaw;$('#eyeSize').value=appearance.eyeSize;$('#trait').value=appearance.trait;$('#aspiration').value=appearance.aspiration;$('#hudName').textContent=appearance.name}catch{}}load();hud();portrait();rebuildCharacter();

async function getPeer(){if(peer)return peer;$('#networkStatus').textContent='Iniciando conexión P2P…';const mod=await import('https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm');const P=mod.default||mod.Peer;peer=new P();peer.on('connection',connect);peer.on('error',e=>$('#networkStatus').textContent='Red: '+e.type);return peer}
function connect(c){network=c;$('#networkStatus').textContent='Conectado con otro jugador.';remoteHolder.visible=true;remoteHolder.clear();remoteHolder.add(fallbackHuman());c.on('data',d=>{if(d?.type==='state'){remoteHolder.position.set(d.x,0,d.z);remoteHolder.rotation.y=d.r||0;remoteHolder.visible=true}});c.on('close',()=>{remoteHolder.visible=false;$('#networkStatus').textContent='El otro jugador salió.'})}
$('#createRoom').onclick=async()=>{try{const p=await getPeer(),ready=id=>{$('#roomCode').value=id;$('#networkStatus').textContent='Sala lista. Comparte este código.'};p.id?ready(p.id):p.once('open',ready)}catch{$('#networkStatus').textContent='No fue posible crear la sala.'}};$('#joinRoom').onclick=async()=>{const id=$('#roomCode').value.trim();if(!id)return notify('Escribe un código de sala');try{const p=await getPeer(),fn=()=>connect(p.connect(id,{reliable:true}));p.id?fn():p.once('open',fn);setTimeout(()=>setMode('game'),450)}catch{$('#networkStatus').textContent='No fue posible unirse.'}};
function sendState(force=false){if(!network?.open)return;const n=performance.now();if(!force&&n-lastNetwork<90)return;lastNetwork=n;network.send({type:'state',x:player.pos.x,z:player.pos.z,r:player.holder.rotation.y})}

const clock=new THREE.Clock();let lastSave=0;function loop(){requestAnimationFrame(loop);const dt=Math.min(.05,clock.getDelta()),t=performance.now()/1000;let moving=false;if(mode==='game'&&!player.action?.locked){let dx=0,dz=0;if(keys.has('w')||keys.has('arrowup'))dz--;if(keys.has('s')||keys.has('arrowdown'))dz++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dz){manualStep(dx,dz,dt*1.95);moving=true}else if(player.path.length){const target=player.path[0],v=target.clone().sub(player.pos),d=v.length();if(d<.08){player.pos.copy(target);player.holder.position.x=player.pos.x;player.holder.position.z=player.pos.z;player.path.shift();if(!player.path.length&&player.action?.pending)execute(player.action)}else{const q=Math.min(d,dt*1.85),nx=player.pos.x+v.x/d*q,nz=player.pos.z+v.z/d*q,ignore=player.action?.id||null;if(!isBlocked(nx,nz,ignore)){player.pos.set(nx,0,nz);player.holder.position.x=nx;player.holder.position.z=nz;player.holder.rotation.y=Math.atan2(v.x,v.z);moving=true;sendState()}else{player.path=[];player.action=null;notify('No encuentro un camino')}}}}animateRig(t,moving);if(mode==='game'&&speed){const f=dt*speed;needs.hunger=Math.max(0,needs.hunger-f*.034);needs.energy=Math.max(0,needs.energy-f*.026);needs.hygiene=Math.max(0,needs.hygiene-f*.018);needs.bladder=Math.max(0,needs.bladder-f*.031);needs.fun=Math.max(0,needs.fun-f*.017);needs.social=Math.max(0,needs.social-f*.014);simMinutes+=f*.7;hud();const day=Math.floor(simMinutes/1440),min=Math.floor(simMinutes%1440);$('#clockText').textContent=`${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'][day%7]} ${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`}if(tvOn){const c=.45+.12*Math.sin(t*2.2);screenMat.emissive.setRGB(.12+c*.2,.34+c*.24,.49+c*.25)}if(performance.now()-lastSave>5000){lastSave=performance.now();save()}if(mode==='menu'){worldCam.position.x=10.9+Math.sin(t*.08)*1.0;worldCam.position.z=10.9+Math.cos(t*.08)*.95;worldCtl.update()}else if(mode==='game')worldCtl.update();else studioCtl.update();renderer.render(mode==='creator'?studio:world,mode==='creator'?studioCam:worldCam)}loop();
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);worldCam.aspect=studioCam.aspect=innerWidth/innerHeight;worldCam.updateProjectionMatrix();studioCam.updateProjectionMatrix()});