import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js/+esm';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js/+esm';
import {RoomEnvironment} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/environments/RoomEnvironment.js/+esm';
import {RoundedBoxGeometry} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/geometries/RoundedBoxGeometry.js/+esm';
import * as SkeletonUtils from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/utils/SkeletonUtils.js/+esm';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const COLORS={skin:['#f2cfb5','#dda580','#bf7e59','#8d563c','#593325'],hair:['#1d1714','#493022','#8b5934','#d0a066','#8d3829'],eye:['#4b3224','#6d7554','#6e8289','#365b78','#5d4d3b'],outfit:['#d8d2c8','#2f3438','#9b826b','#657369','#756472']};
const appearance={name:'Valentina',gender:'fem',skin:1,hair:0,eye:0,hairStyle:0,body:100,height:100,outfit:0,faceWidth:100,jaw:100,eyeSize:100,trait:'Sociable',aspiration:'Vida equilibrada'};
const needs={hunger:78,energy:76,hygiene:75,bladder:72,fun:72,social:70};
let simMinutes=555,speed=1,mode='menu',selected=null,tvOn=false,network=null,peer=null,lastNetwork=0;

const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;$('#game').appendChild(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const world=new THREE.Scene();world.background=new THREE.Color('#78858d');world.environment=environment;const studio=new THREE.Scene();studio.background=new THREE.Color('#747878');studio.environment=environment;
const worldCam=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.05,80),studioCam=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.05,40);worldCam.position.set(10.7,7.7,10.7);studioCam.position.set(0,1.45,4.15);
const worldCtl=new OrbitControls(worldCam,renderer.domElement);worldCtl.target.set(0,.85,0);worldCtl.enableDamping=true;worldCtl.minDistance=5.2;worldCtl.maxDistance=17;worldCtl.maxPolarAngle=1.48;
const studioCtl=new OrbitControls(studioCam,renderer.domElement);studioCtl.target.set(0,1.02,0);studioCtl.enableDamping=true;studioCtl.enablePan=false;studioCtl.minDistance=2.1;studioCtl.maxDistance=5;studioCtl.maxPolarAngle=1.48;

function tex(draw,w=512,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
const wood=tex((c,w,h)=>{c.fillStyle='#7f6044';c.fillRect(0,0,w,h);for(let y=0;y<h;y+=64){c.fillStyle=y%128?'#86664a':'#79593f';c.fillRect(0,y,w,61);c.strokeStyle='#563d2b';c.lineWidth=3;c.beginPath();c.moveTo(0,y+62);c.lineTo(w,y+62);c.stroke();for(let j=0;j<12;j++){const yy=y+8+Math.random()*46;c.strokeStyle='rgba(30,18,11,.09)';c.lineWidth=1;c.beginPath();c.moveTo(0,yy);c.bezierCurveTo(w*.3,yy+8*Math.random()-4,w*.7,yy+8*Math.random()-4,w,yy);c.stroke()}}});wood.repeat.set(2.5,3.3);
const tiles=tex((c,w,h)=>{c.fillStyle='#c8c7c2';c.fillRect(0,0,w,h);c.strokeStyle='#9da09e';c.lineWidth=4;for(let x=0;x<=w;x+=128){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<=h;y+=128){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}});tiles.repeat.set(2.2,3.5);
const fabric=tex((c,w,h)=>{c.fillStyle='#606462';c.fillRect(0,0,w,h);c.strokeStyle='rgba(255,255,255,.035)';for(let i=0;i<w;i+=3){c.beginPath();c.moveTo(i,0);c.lineTo(i,h);c.stroke()}for(let i=0;i<h;i+=3){c.beginPath();c.moveTo(0,i);c.lineTo(w,i);c.stroke()}});fabric.repeat.set(4,4);
const city=tex((c,w,h)=>{let g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#7695ad');g.addColorStop(.42,'#d99d79');g.addColorStop(.66,'#555866');g.addColorStop(1,'#171b22');c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle='#222833';for(let i=0;i<50;i++){let x=Math.random()*w,bw=8+Math.random()*25,bh=35+Math.random()*175;c.fillRect(x,h-bh,bw,bh);c.fillStyle='rgba(255,211,128,.7)';for(let yy=h-bh+12;yy<h-8;yy+=14)for(let xx=x+5;xx<x+bw-4;xx+=9)if(Math.random()>.6)c.fillRect(xx,yy,2.5,4);c.fillStyle='#222833'}c.fillStyle='#ffd4a0';c.globalAlpha=.8;c.beginPath();c.arc(w*.76,h*.29,20,0,7);c.fill();c.globalAlpha=1});
const M={wall:new THREE.MeshStandardMaterial({color:'#d7d0c4',roughness:.92}),wall2:new THREE.MeshStandardMaterial({color:'#c9c1b5',roughness:.92}),wood:new THREE.MeshStandardMaterial({map:wood,roughness:.8}),tile:new THREE.MeshStandardMaterial({map:tiles,roughness:.34}),white:new THREE.MeshStandardMaterial({color:'#eee9e0',roughness:.88}),darkWood:new THREE.MeshStandardMaterial({color:'#5a4333',roughness:.72}),black:new THREE.MeshStandardMaterial({color:'#151719',roughness:.24,metalness:.25}),fabric:new THREE.MeshStandardMaterial({map:fabric,roughness:.96}),chrome:new THREE.MeshStandardMaterial({color:'#a9b0b4',roughness:.16,metalness:.82}),glass:new THREE.MeshPhysicalMaterial({color:'#b9d0d7',roughness:.05,transmission:.58,transparent:true,opacity:.47,metalness:.04}),rug:new THREE.MeshStandardMaterial({color:'#b6aea1',roughness:1}),green:new THREE.MeshStandardMaterial({color:'#4d684a',roughness:.92})};
const rb=(s,p,m=M.white,r=.08)=>{const o=new THREE.Mesh(new RoundedBoxGeometry(s[0],s[1],s[2],5,r),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const bx=(s,p,m=M.white)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const cy=(r1,r2,h,p,m=M.white)=>{const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,32),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const sp=(r,p,m=M.white)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(r,30,20),m);o.position.set(...p);o.castShadow=true;return o};

const home=new THREE.Group();world.add(home);const objects={},collisions=[];
function interactive(id,label,desc,group,approach,actions,bounds){group.traverse(o=>{if(o.isMesh)o.userData.interactive=id});home.add(group);objects[id]={id,label,desc,group,approach:new THREE.Vector3(...approach),actions};if(bounds)collisions.push({id,...bounds})}
function buildHome(){
 const f=new THREE.Mesh(new THREE.PlaneGeometry(12,10),M.wood);f.rotation.x=-Math.PI/2;f.receiveShadow=true;f.userData.floor=true;home.add(f);const bf=new THREE.Mesh(new THREE.PlaneGeometry(2.55,4.5),M.tile);bf.rotation.x=-Math.PI/2;bf.position.set(4.55,.018,2.45);bf.receiveShadow=true;bf.userData.floor=true;home.add(bf);
 home.add(bx([12,3.5,.16],[0,1.75,-5],M.wall),bx([.16,3.5,10],[-6,1.75,0],M.wall),bx([.14,3.2,3.9],[3.3,1.6,3.02],M.wall2),bx([2.7,3.2,.14],[4.65,1.6,4.87],M.wall2));
 const skyline=new THREE.Mesh(new THREE.PlaneGeometry(4.35,2.38),new THREE.MeshBasicMaterial({map:city,toneMapped:false}));skyline.position.set(-2.85,1.95,-4.9);home.add(skyline);const fm=new THREE.MeshStandardMaterial({color:'#1d2225',roughness:.24,metalness:.55});home.add(bx([4.55,.07,.08],[-2.85,.76,-4.78],fm),bx([4.55,.07,.08],[-2.85,3.13,-4.78],fm),bx([.07,2.4,.08],[-5.1,1.95,-4.78],fm),bx([.07,2.4,.08],[-.6,1.95,-4.78],fm),bx([.05,2.36,.08],[-2.85,1.95,-4.76],fm));
 const bed=new THREE.Group();bed.position.set(-3.55,0,-2.55);bed.add(rb([3.18,.42,2.22],[0,.28,0],M.darkWood,.08),rb([3.03,.33,2.08],[0,.58,0],M.white,.14),rb([2.96,.21,1.53],[0,.79,.2],new THREE.MeshStandardMaterial({color:'#aaa195',roughness:.98}),.09),rb([1.13,.2,.58],[-.68,.91,-.62],M.white,.15),rb([1.13,.2,.58],[.68,.91,-.62],M.white,.15),rb([3.2,1.24,.16],[0,1.13,-1.02],M.darkWood,.05));interactive('bed','Cama','Cama doble con colchón, almohadas y ropa de cama.',bed,[-1.75,0,-1.1],[['Dormir','sleep'],['Sentarse','sitBed'],['Hacer la cama','makeBed']],{x:-3.55,z:-2.55,w:3.35,d:2.45});
 home.add(rb([.72,.72,.7],[-5.1,.38,-2.7],M.darkWood,.07),cy(.16,.18,.08,[-5.1,.78,-2.7],M.chrome),cy(.035,.035,.52,[-5.1,1.08,-2.7],M.chrome),cy(.28,.18,.32,[-5.1,1.43,-2.7],new THREE.MeshStandardMaterial({color:'#ead8b6',roughness:.85})));
 const tv=new THREE.Group();tv.position.set(1.05,0,-4.72);tv.add(rb([3.0,1.68,.12],[0,1.72,0],M.black,.06));screenMat=new THREE.MeshStandardMaterial({color:'#101315',roughness:.17,emissive:'#000',emissiveIntensity:0});tv.add(bx([2.76,1.43,.035],[0,1.72,.08],screenMat),rb([3.45,.54,.68],[0,.38,.34],M.darkWood,.07));interactive('tv','Televisor','Televisor grande frente al sofá.',tv,[2.9,0,-2.7],[['Ver televisión','watchTV'],['Encender / apagar','toggleTV']],{x:1.05,z:-4.45,w:3.7,d:.85});
 const sofa=new THREE.Group();sofa.position.set(1.0,0,-1.65);sofa.add(rb([2.9,.62,1.18],[0,.46,0],M.fabric,.16),rb([2.72,.72,.32],[0,.96,.38],M.fabric,.13),rb([.3,.57,1.1],[-1.34,.73,0],M.fabric,.12),rb([.3,.57,1.1],[1.34,.73,0],M.fabric,.12));interactive('sofa','Sofá','Sofá tapizado de tres plazas.',sofa,[1.0,0,-.42],[['Sentarse','sitSofa'],['Relajarse','relax']],{x:1,z:-1.65,w:3.1,d:1.4});
 const rug=new THREE.Mesh(new THREE.PlaneGeometry(4.1,2.6),M.rug);rug.rotation.x=-Math.PI/2;rug.position.set(1,.025,-1.65);rug.receiveShadow=true;home.add(rug);
 const toilet=new THREE.Group();toilet.position.set(5.15,0,3.65);toilet.add(rb([.6,.52,.73],[0,.28,0],M.white,.13),rb([.64,.72,.27],[0,.66,.3],M.white,.08));const seat=new THREE.Mesh(new THREE.TorusGeometry(.26,.05,12,30),M.white);seat.rotation.x=Math.PI/2;seat.scale.z=1.25;seat.position.set(0,.58,-.05);toilet.add(seat);interactive('toilet','Inodoro','Inodoro de porcelana del baño privado.',toilet,[5.15,0,2.65],[['Usar','toilet']],{x:5.15,z:3.65,w:.82,d:1.0});
 const sink=new THREE.Group();sink.position.set(4.05,0,3.8);sink.add(rb([1.1,.72,.62],[0,.38,0],M.darkWood,.07),rb([1.03,.22,.6],[0,.81,0],M.white,.1),cy(.035,.035,.34,[0,.98,.14],M.chrome));const mir=new THREE.Mesh(new THREE.PlaneGeometry(1.1,1.25),new THREE.MeshStandardMaterial({color:'#92a1a6',roughness:.07,metalness:.62}));mir.position.set(0,1.72,.33);mir.rotation.y=Math.PI;sink.add(mir);interactive('sink','Lavamanos','Vanitorio con espejo y grifería cromada.',sink,[4.05,0,2.72],[['Lavarse las manos','wash'],['Mirarse al espejo','mirror']],{x:4.05,z:3.8,w:1.25,d:.88});
 const shower=new THREE.Group();shower.position.set(4.65,0,1.25);shower.add(rb([1.82,.13,1.55],[0,.08,0],M.white,.05),bx([.05,2.35,1.55],[-.88,1.2,0],M.glass),bx([1.8,2.35,.05],[0,1.2,-.75],M.glass),cy(.035,.035,1.8,[.55,1.35,-.58],M.chrome),sp(.12,[.55,2.18,-.44],M.chrome));interactive('shower','Ducha','Ducha de vidrio con agua caliente.',shower,[4.65,0,.15],[['Ducharse','shower']],{x:4.65,z:1.25,w:2,d:1.85});
 const table=new THREE.Group();table.position.set(-.3,0,2);table.add(cy(.72,.72,.12,[0,.55,0],M.darkWood),cy(.08,.08,.52,[0,.28,0],M.chrome));home.add(table);collisions.push({id:'table',x:-.3,z:2,w:1.6,d:1.6});
 const plant=new THREE.Group();plant.position.set(2.45,0,-3.75);plant.add(cy(.22,.3,.5,[0,.25,0],new THREE.MeshStandardMaterial({color:'#b7aa96',roughness:.9})));for(let i=0;i<12;i++){const l=sp(.22,[Math.cos(i*.52)*.22,.73+Math.random()*.35,Math.sin(i*.52)*.22],M.green);l.scale.set(.5,1.7,.38);plant.add(l)}home.add(plant);
 const warm=new THREE.DirectionalLight('#ffd1a0',2.5);warm.position.set(-5,7,4);warm.castShadow=true;warm.shadow.mapSize.set(2048,2048);warm.shadow.camera.left=-8;warm.shadow.camera.right=8;warm.shadow.camera.top=8;warm.shadow.camera.bottom=-8;world.add(warm,new THREE.HemisphereLight('#b8cee1','#57473d',1.5));const lamp=new THREE.PointLight('#ffd7a5',13,5,2);lamp.position.set(-5.1,1.55,-2.7);world.add(lamp);const fill=new THREE.PointLight('#fff1dd',9,8,2);fill.position.set(1.7,3.15,.4);world.add(fill);
}
let screenMat;buildHome();

const player={holder:new THREE.Group(),pos:new THREE.Vector3(-.65,0,.8),target:null,action:null,bones:{},source:null};world.add(player.holder);player.holder.position.copy(player.pos);const remoteHolder=new THREE.Group();remoteHolder.visible=false;world.add(remoteHolder);
function localHuman(){const g=new THREE.Group(),skin=new THREE.MeshStandardMaterial({color:COLORS.skin[appearance.skin],roughness:.72}),cloth=new THREE.MeshStandardMaterial({color:COLORS.outfit[appearance.outfit],roughness:.88}),hair=new THREE.MeshStandardMaterial({color:COLORS.hair[appearance.hair],roughness:.9});let head=sp(.23,[0,1.65,0],skin);head.scale.set(.88,1.04,.92);g.add(head);let h=sp(.245,[0,1.79,-.03],hair);h.scale.set(1,.65,1);g.add(h);let torso=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.54,8,18),cloth);torso.position.y=1.1;g.add(torso);for(const x of[-.16,.16]){let leg=new THREE.Mesh(new THREE.CapsuleGeometry(.1,.66,6,12),new THREE.MeshStandardMaterial({color:'#3b3e41',roughness:.9}));leg.position.set(x,.4,0);g.add(leg)}return g}
function fitAvatar(o){o.traverse(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true;x.material=Array.isArray(x.material)?x.material.map(m=>m.clone()):x.material?.clone()}});const b=new THREE.Box3().setFromObject(o),s=b.getSize(new THREE.Vector3()),q=1.72/Math.max(.1,s.y);o.scale.setScalar(q);const b2=new THREE.Box3().setFromObject(o);o.position.y-=b2.min.y;return o}
function applyLook(o){if(!o)return;const base=o.userData.baseScale||o.scale.clone();o.userData.baseScale=base;const body=appearance.body/100,height=appearance.height/100;o.scale.set(base.x*body*(appearance.gender==='masc'?1.04:.98),base.y*height,base.z*body);o.traverse(x=>{if(!x.isMesh||!x.material)return;const n=x.name.toLowerCase(),paint=m=>{if(!m?.color)return;if((n.includes('head')||n.includes('skin'))&&!n.includes('teeth'))m.color.set(COLORS.skin[appearance.skin]);else if(n.includes('hair')||n.includes('brow'))m.color.set(COLORS.hair[appearance.hair]);else if(n.includes('outfit')||n.includes('shirt')||n.includes('top')||n.includes('bottom'))m.color.set(COLORS.outfit[appearance.outfit])};Array.isArray(x.material)?x.material.forEach(paint):paint(x.material)})}
function replaceAvatar(holder,obj){holder.clear();holder.add(obj);applyLook(obj)}
player.holder.add(localHuman());const studioHolder=new THREE.Group();studio.add(studioHolder);studioHolder.add(localHuman());const sFloor=new THREE.Mesh(new THREE.CircleGeometry(3.2,64),new THREE.MeshStandardMaterial({color:'#6a6762',roughness:.8}));sFloor.rotation.x=-Math.PI/2;sFloor.receiveShadow=true;studio.add(sFloor,new THREE.HemisphereLight('#dce7ef','#5b4c44',1.8));const sk=new THREE.DirectionalLight('#ffe2c5',3.5);sk.position.set(4,6,5);sk.castShadow=true;studio.add(sk);const rim=new THREE.SpotLight('#b7d8ff',25,8,.5,.8,1);rim.position.set(-3,4,2);studio.add(rim);
const AVATAR='https://models.readyplayer.me/6185a4acfb622cf1cdc49348.glb?quality=medium&textureSizeLimit=1024';new GLTFLoader().load(AVATAR,g=>{player.source=fitAvatar(g.scene);replaceAvatar(player.holder,SkeletonUtils.clone(player.source));replaceAvatar(studioHolder,SkeletonUtils.clone(player.source));cacheBones();$('#creatorLoading').textContent='Modelo 3D cargado';portrait()},undefined,()=>{$('#creatorLoading').textContent='Modelo externo no disponible; se mantiene el modelo local.'});
function cacheBones(){player.bones={};player.holder.traverse(o=>{if(!o.isBone)return;let n=o.name.toLowerCase();['leftupperleg','rightupperleg','leftupperarm','rightupperarm'].forEach(k=>{if(n.includes(k))player.bones[k]=o})})}
function portrait(){$('#portrait').style.backgroundImage="url('https://models.readyplayer.me/6185a4acfb622cf1cdc49348.png?scene=headshot-circle&size=256')";$('#portrait').style.backgroundColor=COLORS.skin[appearance.skin]}

function isBlocked(x,z,ignore){if(x<-5.65||x>5.65||z<-4.65||z>4.65)return true;for(const c of collisions){if(c.id===ignore)continue;if(Math.abs(x-c.x)<c.w/2+.19&&Math.abs(z-c.z)<c.d/2+.19)return true}return false}
function go(v,action=null){player.target=v.clone();player.action=action}
function step(dx,dz,d=.09){if(mode!=='game'||player.action?.locked)return;const l=Math.hypot(dx,dz)||1,nx=player.pos.x+dx/l*d,nz=player.pos.z+dz/l*d;if(!isBlocked(nx,nz,null)){player.pos.set(nx,0,nz);player.holder.position.x=nx;player.holder.position.z=nz;player.holder.rotation.y=Math.atan2(dx,dz);player.target=null;player.action=null;sendState()}}
function animateRig(t,m){let s=m?Math.sin(t*9)*.5:Math.sin(t*1.7)*.012,b=player.bones;if(b.leftupperleg)b.leftupperleg.rotation.x=s;if(b.rightupperleg)b.rightupperleg.rotation.x=-s;if(b.leftupperarm)b.leftupperarm.rotation.x=-s*.7;if(b.rightupperarm)b.rightupperarm.rotation.x=s*.7;player.holder.position.y=m?Math.abs(Math.sin(t*9))*.014:0}

function choose(id){let o=objects[id];if(!o)return;selected=id;$('#contextTitle').textContent=o.label;$('#contextDescription').textContent=o.desc;let h=$('#contextActions');h.innerHTML='';o.actions.forEach(([label,a])=>{let b=document.createElement('button');b.textContent=label;b.onclick=()=>queue(id,a);h.appendChild(b)});$('#contextMenu').classList.add('on')}
function queue(id,a){let o=objects[id];$('#contextMenu').classList.remove('on');go(o.approach,{id,a,pending:true,locked:false});notify(`Yendo a ${o.label.toLowerCase()}…`)}
function actionDone(ms,msg,change={},pose=null){notify(msg);if(pose)pose();setTimeout(()=>{Object.entries(change).forEach(([k,v])=>needs[k]=Math.min(100,needs[k]+v));player.action=null;player.holder.visible=true;player.holder.rotation.z=0;player.holder.position.y=0;hud();save()},ms)}
function execute(a){a.pending=false;a.locked=true;switch(a.a){case'toggleTV':tvOn=!tvOn;screenMat.color.set(tvOn?'#4f93bb':'#101315');screenMat.emissive.set(tvOn?'#4f93bb':'#000');screenMat.emissiveIntensity=tvOn?1.8:0;player.action=null;notify(tvOn?'Televisor encendido':'Televisor apagado');sendState(true);break;case'watchTV':tvOn=true;screenMat.color.set('#4f93bb');screenMat.emissive.set('#4f93bb');screenMat.emissiveIntensity=1.8;actionDone(4200,'Viendo televisión',{fun:28},()=>{player.holder.position.set(1,.18,-1.6);player.holder.rotation.y=Math.PI});break;case'sitSofa':case'relax':actionDone(3200,a.a==='relax'?'Relajándose':'Sentada en el sofá',{energy:9,fun:8},()=>{player.holder.position.set(1,.17,-1.58);player.holder.rotation.y=Math.PI});break;case'sleep':actionDone(5200,'Durmiendo…',{energy:48},()=>{player.holder.position.set(-3.55,.72,-2.45);player.holder.rotation.z=-Math.PI/2});break;case'sitBed':actionDone(2800,'Descansando en la cama',{energy:11});break;case'makeBed':actionDone(1200,'Cama ordenada');break;case'toilet':actionDone(3000,'Usando el baño',{bladder:50});break;case'wash':actionDone(2200,'Lavándose las manos',{hygiene:18});break;case'mirror':actionDone(2200,'Mirándose al espejo',{fun:4});break;case'shower':player.holder.visible=false;actionDone(4100,'Duchándose',{hygiene:50});break}}
function notify(s){const t=$('#toast');t.textContent=s;t.classList.add('on');clearTimeout(notify.i);notify.i=setTimeout(()=>t.classList.remove('on'),1800)}
function hud(){Object.keys(needs).forEach(k=>{const e=$(`#${k}Bar`);if(e)e.style.width=Math.max(0,Math.min(100,needs[k]))+'%'});let a=Object.values(needs).reduce((x,y)=>x+y,0)/6;$('#mood').textContent=a>68?'● Cómoda':a>44?'● Normal':'● Incómoda'}

const keys=new Set();addEventListener('keydown',e=>{if(!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))keys.add(e.key.toLowerCase())});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let press=null,moved=false;renderer.domElement.addEventListener('pointerdown',e=>{press=[e.clientX,e.clientY];moved=false});renderer.domElement.addEventListener('pointermove',e=>{if(press&&Math.hypot(e.clientX-press[0],e.clientY-press[1])>7)moved=true});renderer.domElement.addEventListener('pointerup',e=>{if(mode!=='game'||moved){press=null;return}mouse.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight)*2+1);ray.setFromCamera(mouse,worldCam);for(const hit of ray.intersectObjects(home.children,true)){let n=hit.object;while(n&&n!==home){if(n.userData?.interactive){choose(n.userData.interactive);press=null;return}n=n.parent}if(hit.object.userData.floor){let p=hit.point.clone();p.y=0;if(!isBlocked(p.x,p.z,null))go(p);press=null;return}}press=null});

function setMode(m){mode=m;$('#menuScreen').classList.toggle('hidden',m!=='menu');$('#creatorScreen').classList.toggle('hidden',m!=='creator');$('#multiplayerScreen').classList.toggle('hidden',m!=='multi');$('#hud').classList.toggle('hidden',m!=='game');worldCtl.enabled=m==='menu'||m==='game';studioCtl.enabled=m==='creator';if(m==='game'){worldCam.position.set(10.7,7.7,10.7);worldCtl.target.set(0,.85,0);worldCtl.update();hud()}save()}
function updateLook(){appearance.name=$('#charName').value.trim()||'Valentina';appearance.hairStyle=+$(`#hairStyle`).value;appearance.body=+$(`#bodySize`).value;appearance.height=+$(`#height`).value;appearance.outfit=+$(`#outfit`).value;appearance.faceWidth=+$(`#faceWidth`).value;appearance.jaw=+$(`#jaw`).value;appearance.eyeSize=+$(`#eyeSize`).value;appearance.trait=$('#trait').value;appearance.aspiration=$('#aspiration').value;if(player.holder.children[0])applyLook(player.holder.children[0]);if(studioHolder.children[0])applyLook(studioHolder.children[0]);$('#hudName').textContent=appearance.name;portrait();save()}
$('#continueBtn').onclick=()=>setMode('game');$('#newGameBtn').onclick=()=>setMode('creator');$('#createBtn').onclick=()=>setMode('creator');$('#multiplayerBtn').onclick=()=>setMode('multi');$('#creatorBack').onclick=()=>setMode('menu');$('#enterHome').onclick=()=>{updateLook();setMode('game')};$('#multiBack').onclick=()=>setMode('menu');$('#editCharacter').onclick=()=>setMode('creator');$('#menuBtn').onclick=()=>setMode('menu');$('#socialBtn').onclick=()=>setMode('multi');$('#settingsBtn').onclick=()=>notify('Calidad gráfica ajustada automáticamente');$('#homeCamera').onclick=()=>{worldCam.position.set(10.7,7.7,10.7);worldCtl.target.set(0,.85,0);worldCtl.update()};
$$('.speed button').forEach(b=>b.onclick=()=>{$$('.speed button').forEach(x=>x.classList.remove('on'));b.classList.add('on');speed=+b.dataset.speed});$$('.creator-nav button').forEach(b=>b.onclick=()=>{$$('.creator-nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$$('.creator-tab').forEach(x=>x.classList.add('hidden'));$(`#tab-${b.dataset.tab}`).classList.remove('hidden')});$$('[data-gender]').forEach(b=>b.onclick=()=>{$$('[data-gender]').forEach(x=>x.classList.remove('on'));b.classList.add('on');appearance.gender=b.dataset.gender;updateLook()});
function swatches(host,arr,key){let h=$(host);arr.forEach((c,i)=>{let b=document.createElement('button');b.className='swatch'+(appearance[key]===i?' on':'');b.style.background=c;b.onclick=()=>{appearance[key]=i;[...h.children].forEach(x=>x.classList.remove('on'));b.classList.add('on');updateLook()};h.appendChild(b)})}swatches('#skinSwatches',COLORS.skin,'skin');swatches('#hairSwatches',COLORS.hair,'hair');swatches('#eyeSwatches',COLORS.eye,'eye');swatches('#outfitSwatches',COLORS.outfit,'outfit');['charName','hairStyle','bodySize','height','outfit','faceWidth','jaw','eyeSize','trait','aspiration'].forEach(id=>$('#'+id)?.addEventListener('input',updateLook));
$$('.mobile-pad button').forEach(b=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];let i;const f=()=>step(d[0],d[1],.1);b.onpointerdown=e=>{e.preventDefault();f();i=setInterval(f,48)};['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>clearInterval(i)))});

function save(){try{localStorage.setItem('sims-tan-v2',JSON.stringify({appearance,needs,simMinutes,p:[player.pos.x,player.pos.z],tvOn}))}catch{}}
function load(){try{let s=JSON.parse(localStorage.getItem('sims-tan-v2')||'null');if(!s)return;Object.assign(appearance,s.appearance||{});Object.assign(needs,s.needs||{});if(s.simMinutes)simMinutes=s.simMinutes;if(s.p){player.pos.set(s.p[0],0,s.p[1]);player.holder.position.copy(player.pos)}tvOn=!!s.tvOn;$('#charName').value=appearance.name;$('#bodySize').value=appearance.body;$('#height').value=appearance.height;$('#outfit').value=appearance.outfit;$('#trait').value=appearance.trait;$('#aspiration').value=appearance.aspiration;$('#hudName').textContent=appearance.name}catch{}}load();portrait();hud();

async function getPeer(){if(peer)return peer;$('#networkStatus').textContent='Iniciando conexión P2P…';const mod=await import('https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm');const P=mod.default||mod.Peer;peer=new P();peer.on('connection',connect);peer.on('error',e=>$('#networkStatus').textContent='Red: '+e.type);return peer}
function connect(c){network=c;$('#networkStatus').textContent='Conectado con otro jugador.';remoteHolder.visible=true;if(player.source)replaceAvatar(remoteHolder,SkeletonUtils.clone(player.source));else if(!remoteHolder.children.length)remoteHolder.add(localHuman());c.on('data',d=>{if(d?.type==='state'){remoteHolder.position.set(d.x,0,d.z);remoteHolder.rotation.y=d.r||0;remoteHolder.visible=true}});c.on('close',()=>{remoteHolder.visible=false;$('#networkStatus').textContent='El otro jugador salió.'})}
$('#createRoom').onclick=async()=>{try{let p=await getPeer();const ready=id=>{$('#roomCode').value=id;$('#networkStatus').textContent='Sala lista. Comparte este código.'};p.id?ready(p.id):p.once('open',ready)}catch{$('#networkStatus').textContent='No fue posible crear la sala.'}};$('#joinRoom').onclick=async()=>{let id=$('#roomCode').value.trim();if(!id)return notify('Escribe un código de sala');try{let p=await getPeer(),fn=()=>connect(p.connect(id,{reliable:true}));p.id?fn():p.once('open',fn);setTimeout(()=>setMode('game'),450)}catch{$('#networkStatus').textContent='No fue posible unirse.'}};
function sendState(force=false){if(!network?.open)return;let n=performance.now();if(!force&&n-lastNetwork<90)return;lastNetwork=n;network.send({type:'state',x:player.pos.x,z:player.pos.z,r:player.holder.rotation.y})}

const clock=new THREE.Clock();let lastSave=0;function loop(){requestAnimationFrame(loop);let dt=Math.min(.05,clock.getDelta()),t=performance.now()/1000,moving=false;if(mode==='game'&&!player.action?.locked){let dx=0,dz=0;if(keys.has('w')||keys.has('arrowup'))dz--;if(keys.has('s')||keys.has('arrowdown'))dz++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dz){step(dx,dz,dt*1.9);moving=true}else if(player.target){let v=player.target.clone().sub(player.pos),d=v.length(),ignore=player.action?.id||null;if(d<.12){player.pos.copy(player.target);player.holder.position.x=player.pos.x;player.holder.position.z=player.pos.z;player.target=null;if(player.action?.pending)execute(player.action)}else{let q=Math.min(d,dt*1.8),nx=player.pos.x+v.x/d*q,nz=player.pos.z+v.z/d*q;if(!isBlocked(nx,nz,ignore)){player.pos.set(nx,0,nz);player.holder.position.x=nx;player.holder.position.z=nz;player.holder.rotation.y=Math.atan2(v.x,v.z);moving=true;sendState()}else{player.target=null;player.action=null;notify('El camino está bloqueado')}}}}animateRig(t,moving);if(mode==='game'&&speed){let f=dt*speed;needs.hunger=Math.max(0,needs.hunger-f*.034);needs.energy=Math.max(0,needs.energy-f*.026);needs.hygiene=Math.max(0,needs.hygiene-f*.018);needs.bladder=Math.max(0,needs.bladder-f*.031);needs.fun=Math.max(0,needs.fun-f*.017);needs.social=Math.max(0,needs.social-f*.014);simMinutes+=f*.7;hud();let day=Math.floor(simMinutes/1440),min=Math.floor(simMinutes%1440);$('#clockText').textContent=`${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'][day%7]} ${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`}if(performance.now()-lastSave>5000){lastSave=performance.now();save()}if(mode==='menu'){worldCam.position.x=10.7+Math.sin(t*.08)*1.1;worldCam.position.z=10.7+Math.cos(t*.08)*1.05;worldCtl.update()}else if(mode==='game')worldCtl.update();else studioCtl.update();renderer.render(mode==='creator'?studio:world,mode==='creator'?studioCam:worldCam)}loop();
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);worldCam.aspect=studioCam.aspect=innerWidth/innerHeight;worldCam.updateProjectionMatrix();studioCam.updateProjectionMatrix()});
