import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js/+esm';
import {RoomEnvironment} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/environments/RoomEnvironment.js/+esm';
import {RoundedBoxGeometry} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/geometries/RoundedBoxGeometry.js/+esm';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const COLORS={skin:['#f2cfb5','#dda580','#bf7e59','#8d563c','#593325'],hair:['#1d1714','#493022','#8b5934','#d0a066','#8d3829'],eye:['#4b3224','#6d7554','#6e8289','#365b78','#5d4d3b'],outfit:['#d8d2c8','#2f3438','#9b826b','#657369','#756472']};
const appearance={name:'Valentina',gender:'fem',skin:1,hair:0,eye:0,hairStyle:0,body:100,height:100,outfit:0,faceWidth:100,jaw:100,eyeSize:100,trait:'Sociable',aspiration:'Vida equilibrada'};
const needs={hunger:78,energy:76,hygiene:75,bladder:72,fun:72,social:70};
let simMinutes=555,speed=1,mode='menu',tvOn=false,selected=null,network=null,peer=null,lastNetwork=0,graphicsHigh=true;

const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;$('#game').appendChild(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const world=new THREE.Scene();world.background=new THREE.Color('#74818a');world.environment=environment;
const studio=new THREE.Scene();studio.background=new THREE.Color('#747879');studio.environment=environment;
const worldCam=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.05,90),studioCam=new THREE.PerspectiveCamera(33,innerWidth/innerHeight,.05,40);
worldCam.position.set(10.6,8.4,10.6);studioCam.position.set(0,1.45,4.05);
const worldCtl=new OrbitControls(worldCam,renderer.domElement);worldCtl.target.set(0,.82,0);worldCtl.enableDamping=true;worldCtl.dampingFactor=.06;worldCtl.minDistance=6;worldCtl.maxDistance=16;worldCtl.minPolarAngle=.55;worldCtl.maxPolarAngle=1.18;
const studioCtl=new OrbitControls(studioCam,renderer.domElement);studioCtl.target.set(0,1.02,0);studioCtl.enableDamping=true;studioCtl.enablePan=false;studioCtl.minDistance=2.25;studioCtl.maxDistance=5;studioCtl.maxPolarAngle=1.48;

function tex(draw,w=512,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t}
const wood=tex((c,w,h)=>{c.fillStyle='#806148';c.fillRect(0,0,w,h);for(let y=0;y<h;y+=64){c.fillStyle=y%128?'#86664c':'#785a42';c.fillRect(0,y,w,61);c.strokeStyle='#543e2f';c.lineWidth=3;c.beginPath();c.moveTo(0,y+62);c.lineTo(w,y+62);c.stroke();for(let j=0;j<14;j++){const yy=y+7+Math.random()*47;c.strokeStyle='rgba(35,20,12,.10)';c.lineWidth=1;c.beginPath();c.moveTo(0,yy);c.bezierCurveTo(w*.3,yy+8*Math.random()-4,w*.7,yy+8*Math.random()-4,w,yy);c.stroke()}}});wood.repeat.set(2.5,3.3);
const tiles=tex((c,w,h)=>{c.fillStyle='#c9c8c4';c.fillRect(0,0,w,h);c.strokeStyle='#9fa19f';c.lineWidth=4;for(let x=0;x<=w;x+=128){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<=h;y+=128){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}});tiles.repeat.set(2.1,3.4);
const fabric=tex((c,w,h)=>{c.fillStyle='#666966';c.fillRect(0,0,w,h);c.strokeStyle='rgba(255,255,255,.04)';for(let i=0;i<w;i+=3){c.beginPath();c.moveTo(i,0);c.lineTo(i,h);c.stroke()}for(let i=0;i<h;i+=3){c.beginPath();c.moveTo(0,i);c.lineTo(w,i);c.stroke()}});fabric.repeat.set(4,4);
const city=tex((c,w,h)=>{let g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#6f91aa');g.addColorStop(.39,'#d59b78');g.addColorStop(.66,'#555965');g.addColorStop(1,'#171b22');c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle='#242a34';for(let i=0;i<52;i++){let x=Math.random()*w,bw=8+Math.random()*26,bh=35+Math.random()*178;c.fillRect(x,h-bh,bw,bh);c.fillStyle='rgba(255,213,130,.72)';for(let yy=h-bh+12;yy<h-8;yy+=14)for(let xx=x+5;xx<x+bw-4;xx+=9)if(Math.random()>.61)c.fillRect(xx,yy,2.5,4);c.fillStyle='#242a34'}c.fillStyle='#ffd39c';c.globalAlpha=.8;c.beginPath();c.arc(w*.77,h*.27,20,0,7);c.fill();c.globalAlpha=1});
const art=tex((c,w,h)=>{c.fillStyle='#d8cfc3';c.fillRect(0,0,w,h);c.fillStyle='#4f5e58';c.fillRect(55,80,130,290);c.fillStyle='#9b7c61';c.fillRect(200,45,110,345);c.fillStyle='#7c8f91';c.beginPath();c.arc(392,212,92,0,7);c.fill();c.fillStyle='#c7ad8d';c.fillRect(342,305,105,70)});
const M={wall:new THREE.MeshStandardMaterial({color:'#d8d1c6',roughness:.93}),wall2:new THREE.MeshStandardMaterial({color:'#c8c0b5',roughness:.93}),wood:new THREE.MeshStandardMaterial({map:wood,roughness:.8}),tile:new THREE.MeshStandardMaterial({map:tiles,roughness:.34}),white:new THREE.MeshStandardMaterial({color:'#eee9e0',roughness:.88}),darkWood:new THREE.MeshStandardMaterial({color:'#5a4435',roughness:.72}),black:new THREE.MeshStandardMaterial({color:'#151719',roughness:.24,metalness:.25}),fabric:new THREE.MeshStandardMaterial({map:fabric,roughness:.96}),chrome:new THREE.MeshStandardMaterial({color:'#a9b0b4',roughness:.16,metalness:.82}),glass:new THREE.MeshPhysicalMaterial({color:'#bdd2d8',roughness:.06,transmission:.54,transparent:true,opacity:.47,metalness:.04}),rug:new THREE.MeshStandardMaterial({color:'#b7aea1',roughness:1}),green:new THREE.MeshStandardMaterial({color:'#4f684a',roughness:.92}),ceramic:new THREE.MeshStandardMaterial({color:'#f4f1eb',roughness:.42})};
const rb=(s,p,m=M.white,r=.08)=>{const o=new THREE.Mesh(new RoundedBoxGeometry(s[0],s[1],s[2],5,r),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const bx=(s,p,m=M.white)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const cy=(r1,r2,h,p,m=M.white,seg=32)=>{const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,seg),m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o};
const sp=(r,p,m=M.white,seg=30)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(r,seg,20),m);o.position.set(...p);o.castShadow=true;return o};

const home=new THREE.Group();world.add(home);const objects={},collisions=[];
function interactive(id,label,desc,group,approach,actions,bounds){group.traverse(o=>{if(o.isMesh)o.userData.interactive=id});home.add(group);objects[id]={id,label,desc,group,approach:new THREE.Vector3(...approach),actions};if(bounds)collisions.push({id,...bounds})}
function collision(id,x,z,w,d){collisions.push({id,x,z,w,d})}
let screenMat;
function buildHome(){
 const f=new THREE.Mesh(new THREE.PlaneGeometry(12,10),M.wood);f.rotation.x=-Math.PI/2;f.receiveShadow=true;f.userData.floor=true;home.add(f);
 const bf=new THREE.Mesh(new THREE.PlaneGeometry(2.55,4.5),M.tile);bf.rotation.x=-Math.PI/2;bf.position.set(4.55,.018,2.45);bf.receiveShadow=true;bf.userData.floor=true;home.add(bf);
 home.add(bx([12,3.5,.16],[0,1.75,-5],M.wall),bx([.16,3.5,10],[-6,1.75,0],M.wall),bx([.14,3.2,3.88],[3.3,1.6,3.03],M.wall2),bx([2.7,3.2,.14],[4.65,1.6,4.87],M.wall2));collision('partition',3.3,3.03,.22,3.95);
 const skyline=new THREE.Mesh(new THREE.PlaneGeometry(4.35,2.38),new THREE.MeshBasicMaterial({map:city,toneMapped:false}));skyline.position.set(-2.85,1.95,-4.9);home.add(skyline);
 const fm=new THREE.MeshStandardMaterial({color:'#1d2225',roughness:.24,metalness:.55});home.add(bx([4.55,.07,.08],[-2.85,.76,-4.78],fm),bx([4.55,.07,.08],[-2.85,3.13,-4.78],fm),bx([.07,2.4,.08],[-5.1,1.95,-4.78],fm),bx([.07,2.4,.08],[-.6,1.95,-4.78],fm),bx([.05,2.36,.08],[-2.85,1.95,-4.76],fm));
 const bed=new THREE.Group();bed.position.set(-3.52,0,-2.5);bed.add(rb([3.2,.42,2.25],[0,.28,0],M.darkWood,.08),rb([3.05,.34,2.08],[0,.59,0],M.white,.14),rb([2.98,.2,1.55],[0,.79,.2],new THREE.MeshStandardMaterial({color:'#aaa296',roughness:.98}),.09),rb([1.13,.2,.58],[-.68,.91,-.62],M.white,.15),rb([1.13,.2,.58],[.68,.91,-.62],M.white,.15),rb([3.22,1.25,.16],[0,1.13,-1.03],M.darkWood,.05));interactive('bed','Cama','Cama doble con colchón, almohadas y ropa de cama.',bed,[-3.52,0,-.95],[['Dormir','sleep'],['Sentarse','sitBed'],['Hacer la cama','makeBed']],{x:-3.52,z:-2.5,w:3.4,d:2.5});
 const night=rb([.76,.72,.72],[-5.14,.38,-2.65],M.darkWood,.07);home.add(night,rb([.52,.08,.44],[-5.14,.48,-2.25],new THREE.MeshStandardMaterial({color:'#34383a',roughness:.6}),.04),cy(.16,.18,.08,[-5.14,.79,-2.65],M.chrome),cy(.035,.035,.52,[-5.14,1.08,-2.65],M.chrome),cy(.28,.18,.32,[-5.14,1.43,-2.65],new THREE.MeshStandardMaterial({color:'#ead8b6',roughness:.85})));collision('night',-5.14,-2.65,.9,.9);
 const tv=new THREE.Group();tv.position.set(1.05,0,-4.72);tv.add(rb([3.02,1.7,.12],[0,1.72,0],M.black,.06));screenMat=new THREE.MeshStandardMaterial({color:'#101315',roughness:.16,emissive:'#000',emissiveIntensity:0});tv.add(bx([2.78,1.45,.035],[0,1.72,.08],screenMat),rb([3.48,.55,.7],[0,.38,.35],M.darkWood,.07),bx([2.7,.08,.48],[0,.65,.38],M.black));interactive('tv','Televisor','Televisor grande frente al sofá.',tv,[1.05,0,-2.7],[['Ver televisión','watchTV'],['Encender / apagar','toggleTV']],{x:1.05,z:-4.45,w:3.75,d:.88});
 const sofa=new THREE.Group();sofa.position.set(1.0,0,-1.52);sofa.add(rb([2.92,.62,1.18],[0,.46,0],M.fabric,.16),rb([2.74,.72,.32],[0,.96,.38],M.fabric,.13),rb([.3,.58,1.1],[-1.35,.73,0],M.fabric,.12),rb([.3,.58,1.1],[1.35,.73,0],M.fabric,.12),rb([1.15,.12,.58],[-.65,.77,-.05],new THREE.MeshStandardMaterial({color:'#777972',roughness:.96}),.09),rb([1.15,.12,.58],[.65,.77,-.05],new THREE.MeshStandardMaterial({color:'#777972',roughness:.96}),.09));interactive('sofa','Sofá','Sofá tapizado de tres plazas.',sofa,[1.0,0,-.45],[['Sentarse','sitSofa'],['Relajarse','relax']],{x:1,z:-1.52,w:3.15,d:1.45});
 const rug=new THREE.Mesh(new THREE.PlaneGeometry(4.25,2.7),M.rug);rug.rotation.x=-Math.PI/2;rug.position.set(1,.025,-1.65);rug.receiveShadow=true;home.add(rug);
 const coffee=new THREE.Group();coffee.position.set(1.0,0,-.05);coffee.add(rb([1.55,.12,.78],[0,.43,0],M.darkWood,.07),cy(.055,.055,.42,[-.62,.21,-.27],M.chrome),cy(.055,.055,.42,[.62,.21,-.27],M.chrome),cy(.055,.055,.42,[-.62,.21,.27],M.chrome),cy(.055,.055,.42,[.62,.21,.27],M.chrome));home.add(coffee);collision('coffee',1,-.05,1.75,.98);
 const dining=new THREE.Group();dining.position.set(-1.25,0,2.25);dining.add(cy(.76,.76,.12,[0,.62,0],M.darkWood),cy(.09,.09,.58,[0,.3,0],M.chrome));home.add(dining);collision('dining',-1.25,2.25,1.7,1.7);
 for(const a of[0,Math.PI]){const ch=new THREE.Group();ch.position.set(-1.25+Math.sin(a)*1.25,0,2.25+Math.cos(a)*1.25);ch.add(rb([.55,.48,.55],[0,.38,0],M.darkWood,.07),rb([.55,.68,.13],[0,.86,.23],M.darkWood,.05));ch.rotation.y=a;home.add(ch);collision('chair'+a,ch.position.x,ch.position.z,.7,.72)}
 const toilet=new THREE.Group();toilet.position.set(5.15,0,3.68);toilet.add(rb([.6,.52,.73],[0,.28,0],M.ceramic,.13),rb([.64,.72,.27],[0,.66,.3],M.ceramic,.08));const seat=new THREE.Mesh(new THREE.TorusGeometry(.26,.05,12,30),M.ceramic);seat.rotation.x=Math.PI/2;seat.scale.z=1.25;seat.position.set(0,.58,-.05);toilet.add(seat);interactive('toilet','Inodoro','Inodoro de porcelana del baño privado.',toilet,[5.15,0,2.72],[['Usar','toilet']],{x:5.15,z:3.68,w:.86,d:1.05});
 const sink=new THREE.Group();sink.position.set(4.03,0,3.82);sink.add(rb([1.1,.72,.62],[0,.38,0],M.darkWood,.07),rb([1.03,.22,.6],[0,.81,0],M.ceramic,.1),cy(.035,.035,.34,[0,.98,.14],M.chrome));const bowl=new THREE.Mesh(new THREE.TorusGeometry(.31,.06,10,28),M.ceramic);bowl.rotation.x=Math.PI/2;bowl.scale.z=.7;bowl.position.set(0,.88,-.05);sink.add(bowl);const mir=new THREE.Mesh(new THREE.PlaneGeometry(1.12,1.28),new THREE.MeshStandardMaterial({color:'#94a2a7',roughness:.06,metalness:.68}));mir.position.set(0,1.73,.33);mir.rotation.y=Math.PI;sink.add(mir);interactive('sink','Lavamanos','Vanitorio con espejo y grifería cromada.',sink,[4.03,0,2.72],[['Lavarse las manos','wash'],['Mirarse al espejo','mirror']],{x:4.03,z:3.82,w:1.28,d:.9});
 const shower=new THREE.Group();shower.position.set(4.65,0,1.25);shower.add(rb([1.82,.13,1.55],[0,.08,0],M.ceramic,.05),bx([.05,2.35,1.55],[-.88,1.2,0],M.glass),bx([1.8,2.35,.05],[0,1.2,-.75],M.glass),cy(.035,.035,1.8,[.55,1.35,-.58],M.chrome),sp(.12,[.55,2.18,-.44],M.chrome));interactive('shower','Ducha','Ducha de vidrio con agua caliente.',shower,[4.65,0,.12],[['Ducharse','shower']],{x:4.65,z:1.25,w:2,d:1.9});
 const bathMat=new THREE.Mesh(new THREE.PlaneGeometry(1.45,.72),new THREE.MeshStandardMaterial({color:'#8a8f8c',roughness:1}));bathMat.rotation.x=-Math.PI/2;bathMat.position.set(4.65,.028,2.35);home.add(bathMat);
 home.add(cy(.025,.025,1.1,[5.55,1.25,2.15],M.chrome));const towel=rb([.62,.7,.045],[5.53,1.18,2.15],new THREE.MeshStandardMaterial({color:'#d8d2c8',roughness:1}),.03);towel.rotation.y=Math.PI/2;home.add(towel);
 const plant=new THREE.Group();plant.position.set(2.55,0,-3.72);plant.add(cy(.23,.31,.52,[0,.26,0],new THREE.MeshStandardMaterial({color:'#b8aa96',roughness:.9})));for(let i=0;i<13;i++){const l=sp(.22,[Math.cos(i*.51)*.22,.74+Math.random()*.34,Math.sin(i*.51)*.22],M.green);l.scale.set(.5,1.72,.38);plant.add(l)}home.add(plant);collision('plant',2.55,-3.72,.72,.72);
 const painting=new THREE.Mesh(new THREE.PlaneGeometry(1.85,1.3),new THREE.MeshStandardMaterial({map:art,roughness:.8}));painting.position.set(-.8,2.13,-4.89);home.add(painting,bx([2.05,.06,.07],[-.8,2.82,-4.83],M.darkWood),bx([2.05,.06,.07],[-.8,1.44,-4.83],M.darkWood),bx([.06,1.44,.07],[-1.82,2.13,-4.83],M.darkWood),bx([.06,1.44,.07],[.22,2.13,-4.83],M.darkWood));
 const warm=new THREE.DirectionalLight('#ffd1a0',2.4);warm.position.set(-5,7,4);warm.castShadow=true;warm.shadow.mapSize.set(2048,2048);warm.shadow.camera.left=-8;warm.shadow.camera.right=8;warm.shadow.camera.top=8;warm.shadow.camera.bottom=-8;world.add(warm,new THREE.HemisphereLight('#b9cfe2','#57483e',1.5));const lamp=new THREE.PointLight('#ffd8a6',12,5,2);lamp.position.set(-5.12,1.55,-2.65);world.add(lamp);const fill=new THREE.PointLight('#fff1dd',8,8,2);fill.position.set(1.7,3.15,.4);world.add(fill);
}
buildHome();

function material(color,rough=.75){return new THREE.MeshStandardMaterial({color,roughness:rough})}
function createHuman(){
 const root=new THREE.Group();root.userData.rig={};
 const skin=material(COLORS.skin[appearance.skin],.72),hair=material(COLORS.hair[appearance.hair],.9),eye=material(COLORS.eye[appearance.eye],.35),white=material('#f7f5f0',.5),cloth=material(COLORS.outfit[appearance.outfit],.88),pants=material(appearance.outfit===1?'#23272b':'#3c4144',.9),shoe=material('#242526',.7),lip=material(appearance.gender==='fem'?'#a05f62':'#785453',.8);
 const fw=appearance.faceWidth/100,jw=appearance.jaw/100,es=appearance.eyeSize/100,body=appearance.body/100,height=appearance.height/100,isM=appearance.gender==='masc';
 root.scale.set(body*(isM?1.03:.98),height,body);
 const hips=new THREE.Group();hips.position.y=.82;root.add(hips);
 const torso=new THREE.Mesh(new THREE.CapsuleGeometry(isM?.295:.27,.48,8,18),cloth);torso.position.y=.34;torso.scale.set(isM?1.07:1,1,isM?1.02:.96);hips.add(torso);
 const waist=rb([isM?.49:.44,.16,.28],[0,.03,0],pants,.07);hips.add(waist);
 const neck=cy(.09,.095,.16,[0,.73,0],skin);hips.add(neck);
 const headGroup=new THREE.Group();headGroup.position.set(0,1.55,0);root.add(headGroup);const head=sp(.235,[0,0,0],skin);head.scale.set(.92*fw,1.04,.92);headGroup.add(head);const jaw=sp(.19,[0,-.095,.015],skin);jaw.scale.set(.9*fw*jw,.64,.88);headGroup.add(jaw);
 for(const sx of[-1,1]){const ear=sp(.055,[sx*.22*fw,.005,0],skin,22);ear.scale.set(.55,1,.55);headGroup.add(ear);const eyeWhite=sp(.057,[sx*.085,.025,.206],white,20);eyeWhite.scale.set(1.05*es,.64*es,.38);headGroup.add(eyeWhite);const iris=sp(.027,[sx*.085,.023,.247],eye,18);iris.scale.set(es,es,.32);headGroup.add(iris);const pupil=sp(.011,[sx*.085,.022,.266],material('#111213',.25),14);pupil.scale.set(es,es,.25);headGroup.add(pupil);const brow=rb([.095,.018,.018],[sx*.086,.092,.22],hair,.008);brow.rotation.z=sx*.08;headGroup.add(brow)}
 const nose=sp(.045,[0,-.015,.225],skin,18);nose.scale.set(.58,1.1,.82);headGroup.add(nose);const mouth=rb([.105,.018,.018],[0,-.115,.217],lip,.009);headGroup.add(mouth);
 const hairCap=sp(.245,[0,.105,-.015],hair);hairCap.scale.set(1.02*fw,.72,1.02);headGroup.add(hairCap);if(appearance.hairStyle===0){for(const sx of[-1,1]){const lock=rb([.11,.47,.12],[sx*.185,-.16,-.09],hair,.055);lock.rotation.z=sx*.08;headGroup.add(lock)}const back=rb([.32,.5,.13],[0,-.16,-.19],hair,.07);headGroup.add(back)}else if(appearance.hairStyle===1){const bun=sp(.145,[0,.19,-.2],hair,24);bun.scale.set(1,1,.85);headGroup.add(bun)}else{const fringe=rb([.28,.09,.08],[0,.125,.18],hair,.04);fringe.rotation.z=-.08;headGroup.add(fringe)}
 function limb(side,isArm){const pivot=new THREE.Group();if(isArm)pivot.position.set(side*(isM?.34:.31),1.29,0);else pivot.position.set(side*(isM?.145:.135),.82,0);root.add(pivot);const upperMat=isArm?cloth:pants,rad=isArm?.075:.095,len=isArm?.43:.54;const upper=new THREE.Mesh(new THREE.CapsuleGeometry(rad,len,6,12),upperMat);upper.position.y=-len*.56;pivot.add(upper);if(isArm){const hand=sp(.085,[0,-.54,0],skin,18);hand.scale.set(.8,1.05,.72);pivot.add(hand)}else{const lower=new THREE.Mesh(new THREE.CapsuleGeometry(.082,.38,6,12),pants);lower.position.y=-.63;pivot.add(lower);const foot=rb([.19,.12,.31],[0,-.87,.065],shoe,.06);pivot.add(foot)}return pivot}
 root.userData.rig.leftArm=limb(-1,true);root.userData.rig.rightArm=limb(1,true);root.userData.rig.leftLeg=limb(-1,false);root.userData.rig.rightLeg=limb(1,false);root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return root
}
const player={holder:new THREE.Group(),pos:new THREE.Vector3(-.7,0,.8),path:[],action:null};world.add(player.holder);player.holder.position.copy(player.pos);
const studioHolder=new THREE.Group();studio.add(studioHolder);const remoteHolder=new THREE.Group();remoteHolder.visible=false;world.add(remoteHolder);
function rebuildAvatar(holder){holder.clear();holder.add(createHuman())}
rebuildAvatar(player.holder);rebuildAvatar(studioHolder);rebuildAvatar(remoteHolder);
const sFloor=new THREE.Mesh(new THREE.CircleGeometry(3.2,64),new THREE.MeshStandardMaterial({color:'#686661',roughness:.82}));sFloor.rotation.x=-Math.PI/2;sFloor.receiveShadow=true;studio.add(sFloor,new THREE.HemisphereLight('#dce8f0','#5b4c44',1.8));const sk=new THREE.DirectionalLight('#ffe2c5',3.5);sk.position.set(4,6,5);sk.castShadow=true;studio.add(sk);const rim=new THREE.SpotLight('#badcff',22,8,.5,.8,1);rim.position.set(-3,4,2);studio.add(rim);$('#creatorLoading').textContent='Modelo 3D procedural listo';
function portrait(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');let g=x.createLinearGradient(0,0,0,128);g.addColorStop(0,'#d7e2e8');g.addColorStop(1,'#7f8d93');x.fillStyle=g;x.fillRect(0,0,128,128);x.fillStyle=COLORS.hair[appearance.hair];x.beginPath();x.arc(64,54,35,Math.PI,Math.PI*2);x.fill();x.fillStyle=COLORS.skin[appearance.skin];x.beginPath();x.ellipse(64,60,30*appearance.faceWidth/100,35,0,0,Math.PI*2);x.fill();x.fillStyle=COLORS.eye[appearance.eye];for(const e of[50,78]){x.beginPath();x.arc(e,58,4.3*appearance.eyeSize/100,0,7);x.fill()}x.strokeStyle='#744f4d';x.lineWidth=2;x.beginPath();x.arc(64,70,10,0.2,Math.PI-.2);x.stroke();$('#portrait').style.backgroundImage=`url(${c.toDataURL()})`;$('#portrait').style.backgroundColor=COLORS.skin[appearance.skin]}
portrait();

function isBlocked(x,z,ignore){if(x<-5.62||x>5.62||z<-4.62||z>4.62)return true;for(const c of collisions){if(c.id===ignore)continue;if(Math.abs(x-c.x)<c.w/2+.18&&Math.abs(z-c.z)<c.d/2+.18)return true}return false}
const CELL=.28,X0=-5.55,Z0=-4.55,NX=Math.floor(11.1/CELL)+1,NZ=Math.floor(9.1/CELL)+1;
function findPath(from,to,ignore){const toCell=v=>[Math.max(0,Math.min(NX-1,Math.round((v.x-X0)/CELL))),Math.max(0,Math.min(NZ-1,Math.round((v.z-Z0)/CELL)))],key=(x,z)=>x+','+z;const [sx,sz]=toCell(from),[tx,tz]=toCell(to),open=[{x:sx,z:sz,g:0,f:0}],best=new Map([[key(sx,sz),0]]),came=new Map(),dirs=[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1],[1,1,1.414],[1,-1,1.414],[-1,1,1.414],[-1,-1,1.414]];let guard=0,end=null;while(open.length&&guard++<5000){open.sort((a,b)=>a.f-b.f);const n=open.shift();if(n.x===tx&&n.z===tz){end=n;break}for(const [dx,dz,cost] of dirs){const x=n.x+dx,z=n.z+dz;if(x<0||z<0||x>=NX||z>=NZ)continue;const wx=X0+x*CELL,wz=Z0+z*CELL;if(isBlocked(wx,wz,ignore)&&!(x===tx&&z===tz))continue;const g=n.g+cost,k=key(x,z);if(g>=(best.get(k)??Infinity))continue;best.set(k,g);came.set(k,key(n.x,n.z));const h=Math.hypot(tx-x,tz-z);open.push({x,z,g,f:g+h})}}if(!end)return[to.clone()];const cells=[];let k=key(tx,tz);cells.push([tx,tz]);while(k!==key(sx,sz)){const p=came.get(k);if(!p)break;const [x,z]=p.split(',').map(Number);cells.push([x,z]);k=p}cells.reverse();const path=[];for(let i=1;i<cells.length;i+=2){const [x,z]=cells[i];path.push(new THREE.Vector3(X0+x*CELL,0,Z0+z*CELL))}path.push(to.clone());return path}
function go(v,action=null){player.action=action;player.path=findPath(player.pos,v,action?.id||null)}
function manualStep(dx,dz,d=.09){if(mode!=='game'||player.action?.locked)return;const l=Math.hypot(dx,dz)||1,nx=player.pos.x+dx/l*d,nz=player.pos.z+dz/l*d;if(!isBlocked(nx,nz,null)){player.pos.set(nx,0,nz);player.holder.position.x=nx;player.holder.position.z=nz;player.holder.rotation.y=Math.atan2(dx,dz);player.path=[];player.action=null;sendState()}}
function animateRig(t,moving){const r=player.holder.children[0]?.userData?.rig;if(!r)return;const s=moving?Math.sin(t*9)*.58:Math.sin(t*1.8)*.018;r.leftLeg.rotation.x=s;r.rightLeg.rotation.x=-s;r.leftArm.rotation.x=-s*.72;r.rightArm.rotation.x=s*.72;player.holder.position.y=moving?Math.abs(Math.sin(t*9))*.014:0}

function choose(id){const o=objects[id];if(!o)return;selected=id;$('#contextTitle').textContent=o.label;$('#contextDescription').textContent=o.desc;const h=$('#contextActions');h.innerHTML='';for(const [label,a] of o.actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>queue(id,a);h.appendChild(b)}$('#contextMenu').classList.add('on')}
function queue(id,a){const o=objects[id];$('#contextMenu').classList.remove('on');go(o.approach,{id,a,pending:true,locked:false});notify(`Yendo a ${o.label.toLowerCase()}…`)}
function resetPose(){player.holder.visible=true;player.holder.rotation.z=0;player.holder.rotation.x=0;player.holder.position.set(player.pos.x,0,player.pos.z)}
function actionDone(ms,msg,change={},pose=null){notify(msg);if(pose)pose();setTimeout(()=>{for(const [k,v] of Object.entries(change))needs[k]=Math.min(100,needs[k]+v);player.action=null;resetPose();hud();save()},ms)}
function execute(a){a.pending=false;a.locked=true;switch(a.a){case'toggleTV':tvOn=!tvOn;screenMat.color.set(tvOn?'#4f93bb':'#101315');screenMat.emissive.set(tvOn?'#4f93bb':'#000');screenMat.emissiveIntensity=tvOn?1.7:0;player.action=null;notify(tvOn?'Televisor encendido':'Televisor apagado');sendState(true);break;case'watchTV':tvOn=true;screenMat.color.set('#4f93bb');screenMat.emissive.set('#4f93bb');screenMat.emissiveIntensity=1.7;actionDone(4200,'Viendo televisión',{fun:28},()=>{player.holder.position.set(1,.2,-1.55);player.holder.rotation.y=Math.PI});break;case'sitSofa':case'relax':actionDone(3200,a.a==='relax'?'Relajándose':'Sentada en el sofá',{energy:9,fun:8},()=>{player.holder.position.set(1,.19,-1.5);player.holder.rotation.y=Math.PI});break;case'sleep':actionDone(5200,'Durmiendo…',{energy:48},()=>{player.holder.position.set(-3.52,.78,-2.45);player.holder.rotation.z=-Math.PI/2});break;case'sitBed':actionDone(2800,'Descansando en la cama',{energy:11},()=>{player.holder.position.set(-3.52,.48,-1.72);player.holder.rotation.y=0});break;case'makeBed':actionDone(1200,'Cama ordenada');break;case'toilet':actionDone(3000,'Usando el baño',{bladder:50},()=>{player.holder.position.set(5.15,.14,3.47);player.holder.rotation.y=0});break;case'wash':actionDone(2200,'Lavándose las manos',{hygiene:18},()=>{player.holder.rotation.y=0});break;case'mirror':actionDone(2200,'Mirándose al espejo',{fun:4},()=>{player.holder.rotation.y=0});break;case'shower':player.holder.visible=false;actionDone(4100,'Duchándose',{hygiene:50});break}}
function notify(s){const t=$('#toast');t.textContent=s;t.classList.add('on');clearTimeout(notify.i);notify.i=setTimeout(()=>t.classList.remove('on'),1800)}
function hud(){for(const k of Object.keys(needs)){const e=$(`#${k}Bar`);if(e)e.style.width=Math.max(0,Math.min(100,needs[k]))+'%'}const a=Object.values(needs).reduce((x,y)=>x+y,0)/6;$('#mood').textContent=a>68?'● Cómoda':a>44?'● Normal':'● Incómoda'}

const keys=new Set();addEventListener('keydown',e=>{if(!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))keys.add(e.key.toLowerCase())});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let press=null,moved=false;renderer.domElement.addEventListener('pointerdown',e=>{press=[e.clientX,e.clientY];moved=false});renderer.domElement.addEventListener('pointermove',e=>{if(press&&Math.hypot(e.clientX-press[0],e.clientY-press[1])>7)moved=true});renderer.domElement.addEventListener('pointerup',e=>{if(mode!=='game'||moved){press=null;return}mouse.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight)*2+1);ray.setFromCamera(mouse,worldCam);for(const hit of ray.intersectObjects(home.children,true)){let n=hit.object;while(n&&n!==home){if(n.userData?.interactive){choose(n.userData.interactive);press=null;return}n=n.parent}if(hit.object.userData.floor){const p=hit.point.clone();p.y=0;if(!isBlocked(p.x,p.z,null))go(p);press=null;return}}press=null});

function setMode(m){mode=m;$('#menuScreen').classList.toggle('hidden',m!=='menu');$('#creatorScreen').classList.toggle('hidden',m!=='creator');$('#multiplayerScreen').classList.toggle('hidden',m!=='multi');$('#hud').classList.toggle('hidden',m!=='game');worldCtl.enabled=m==='menu'||m==='game';studioCtl.enabled=m==='creator';if(m==='game'){worldCam.position.set(10.6,8.4,10.6);worldCtl.target.set(0,.82,0);worldCtl.update();hud()}save()}
function updateLook(){appearance.name=$('#charName').value.trim()||'Valentina';appearance.hairStyle=+$('#hairStyle').value;appearance.body=+$('#bodySize').value;appearance.height=+$('#height').value;appearance.outfit=+$('#outfit').value;appearance.faceWidth=+$('#faceWidth').value;appearance.jaw=+$('#jaw').value;appearance.eyeSize=+$('#eyeSize').value;appearance.trait=$('#trait').value;appearance.aspiration=$('#aspiration').value;rebuildAvatar(player.holder);rebuildAvatar(studioHolder);$('#hudName').textContent=appearance.name;portrait();save()}
$('#continueBtn').onclick=()=>setMode('game');$('#newGameBtn').onclick=()=>setMode('creator');$('#createBtn').onclick=()=>setMode('creator');$('#multiplayerBtn').onclick=()=>setMode('multi');$('#creatorBack').onclick=()=>setMode('menu');$('#enterHome').onclick=()=>{updateLook();setMode('game')};$('#multiBack').onclick=()=>setMode('menu');$('#editCharacter').onclick=()=>setMode('creator');$('#menuBtn').onclick=()=>setMode('menu');$('#socialBtn').onclick=()=>setMode('multi');$('#settingsBtn').onclick=()=>{graphicsHigh=!graphicsHigh;renderer.setPixelRatio(Math.min(devicePixelRatio,graphicsHigh?2:1.25));renderer.shadowMap.enabled=graphicsHigh;notify(graphicsHigh?'Calidad alta':'Modo rendimiento')};$('#homeCamera').onclick=()=>{worldCam.position.set(10.6,8.4,10.6);worldCtl.target.set(0,.82,0);worldCtl.update()};
$$('.speed button').forEach(b=>b.onclick=()=>{$$('.speed button').forEach(x=>x.classList.remove('on'));b.classList.add('on');speed=+b.dataset.speed});$$('.creator-nav button').forEach(b=>b.onclick=()=>{$$('.creator-nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$$('.creator-tab').forEach(x=>x.classList.add('hidden'));$(`#tab-${b.dataset.tab}`).classList.remove('hidden')});$$('[data-gender]').forEach(b=>b.onclick=()=>{$$('[data-gender]').forEach(x=>x.classList.remove('on'));b.classList.add('on');appearance.gender=b.dataset.gender;updateLook()});
function swatches(host,arr,key){const h=$(host);arr.forEach((c,i)=>{const b=document.createElement('button');b.className='swatch'+(appearance[key]===i?' on':'');b.style.background=c;b.onclick=()=>{appearance[key]=i;[...h.children].forEach(x=>x.classList.remove('on'));b.classList.add('on');updateLook()};h.appendChild(b)})}swatches('#skinSwatches',COLORS.skin,'skin');swatches('#hairSwatches',COLORS.hair,'hair');swatches('#eyeSwatches',COLORS.eye,'eye');swatches('#outfitSwatches',COLORS.outfit,'outfit');['charName','hairStyle','bodySize','height','outfit','faceWidth','jaw','eyeSize','trait','aspiration'].forEach(id=>$('#'+id)?.addEventListener('input',updateLook));
$$('.mobile-pad button').forEach(b=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];let i;const f=()=>manualStep(d[0],d[1],.1);b.onpointerdown=e=>{e.preventDefault();f();i=setInterval(f,48)};['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>clearInterval(i)))});

function save(){try{localStorage.setItem('sims-tan-final',JSON.stringify({appearance,needs,simMinutes,p:[player.pos.x,player.pos.z],tvOn}))}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem('sims-tan-final')||'null');if(!s)return;Object.assign(appearance,s.appearance||{});Object.assign(needs,s.needs||{});if(s.simMinutes)simMinutes=s.simMinutes;if(s.p){player.pos.set(s.p[0],0,s.p[1]);player.holder.position.copy(player.pos)}tvOn=!!s.tvOn;$('#charName').value=appearance.name;$('#hairStyle').value=appearance.hairStyle;$('#bodySize').value=appearance.body;$('#height').value=appearance.height;$('#outfit').value=appearance.outfit;$('#faceWidth').value=appearance.faceWidth;$('#jaw').value=appearance.jaw;$('#eyeSize').value=appearance.eyeSize;$('#trait').value=appearance.trait;$('#aspiration').value=appearance.aspiration;$('#hudName').textContent=appearance.name;rebuildAvatar(player.holder);rebuildAvatar(studioHolder)}catch{}}load();portrait();hud();

async function getPeer(){if(peer)return peer;$('#networkStatus').textContent='Iniciando conexión P2P…';const mod=await import('https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm');const P=mod.default||mod.Peer;peer=new P();peer.on('connection',connect);peer.on('error',e=>$('#networkStatus').textContent='Red: '+e.type);return peer}
function connect(c){network=c;$('#networkStatus').textContent='Conectado con otro jugador.';remoteHolder.visible=true;rebuildAvatar(remoteHolder);c.on('data',d=>{if(d?.type==='state'){remoteHolder.position.set(d.x,0,d.z);remoteHolder.rotation.y=d.r||0;remoteHolder.visible=true}});c.on('close',()=>{remoteHolder.visible=false;$('#networkStatus').textContent='El otro jugador salió.'})}
$('#createRoom').onclick=async()=>{try{const p=await getPeer(),ready=id=>{$('#roomCode').value=id;$('#networkStatus').textContent='Sala lista. Comparte este código.'};p.id?ready(p.id):p.once('open',ready)}catch{$('#networkStatus').textContent='No fue posible crear la sala.'}};$('#joinRoom').onclick=async()=>{const id=$('#roomCode').value.trim();if(!id)return notify('Escribe un código de sala');try{const p=await getPeer(),fn=()=>connect(p.connect(id,{reliable:true}));p.id?fn():p.once('open',fn);setTimeout(()=>setMode('game'),450)}catch{$('#networkStatus').textContent='No fue posible unirse.'}};
function sendState(force=false){if(!network?.open)return;const n=performance.now();if(!force&&n-lastNetwork<90)return;lastNetwork=n;network.send({type:'state',x:player.pos.x,z:player.pos.z,r:player.holder.rotation.y})}

const clock=new THREE.Clock();let lastSave=0;function loop(){requestAnimationFrame(loop);const dt=Math.min(.05,clock.getDelta()),t=performance.now()/1000;let moving=false;if(mode==='game'&&!player.action?.locked){let dx=0,dz=0;if(keys.has('w')||keys.has('arrowup'))dz--;if(keys.has('s')||keys.has('arrowdown'))dz++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dz){manualStep(dx,dz,dt*1.95);moving=true}else if(player.path.length){const target=player.path[0],v=target.clone().sub(player.pos),d=v.length();if(d<.08){player.pos.copy(target);player.holder.position.x=player.pos.x;player.holder.position.z=player.pos.z;player.path.shift();if(!player.path.length&&player.action?.pending)execute(player.action)}else{const q=Math.min(d,dt*1.85),nx=player.pos.x+v.x/d*q,nz=player.pos.z+v.z/d*q,ignore=player.action?.id||null;if(!isBlocked(nx,nz,ignore)){player.pos.set(nx,0,nz);player.holder.position.x=nx;player.holder.position.z=nz;player.holder.rotation.y=Math.atan2(v.x,v.z);moving=true;sendState()}else{player.path=[];if(player.action?.pending){const o=objects[player.action.id];player.path=findPath(player.pos,o.approach,player.action.id)}if(!player.path.length){player.action=null;notify('No encuentro un camino')}}}}}animateRig(t,moving);if(mode==='game'&&speed){const f=dt*speed;needs.hunger=Math.max(0,needs.hunger-f*.034);needs.energy=Math.max(0,needs.energy-f*.026);needs.hygiene=Math.max(0,needs.hygiene-f*.018);needs.bladder=Math.max(0,needs.bladder-f*.031);needs.fun=Math.max(0,needs.fun-f*.017);needs.social=Math.max(0,needs.social-f*.014);simMinutes+=f*.7;hud();const day=Math.floor(simMinutes/1440),min=Math.floor(simMinutes%1440);$('#clockText').textContent=`${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'][day%7]} ${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`}if(tvOn){const c=.46+.12*Math.sin(t*2.3);screenMat.emissive.setRGB(.12+c*.2,.35+c*.24,.5+c*.25)}if(performance.now()-lastSave>5000){lastSave=performance.now();save()}if(mode==='menu'){worldCam.position.x=10.6+Math.sin(t*.08)*1.05;worldCam.position.z=10.6+Math.cos(t*.08)*1.0;worldCtl.update()}else if(mode==='game')worldCtl.update();else studioCtl.update();renderer.render(mode==='creator'?studio:world,mode==='creator'?studioCam:worldCam)}loop();
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);worldCam.aspect=studioCam.aspect=innerWidth/innerHeight;worldCam.updateProjectionMatrix();studioCam.updateProjectionMatrix()});